export const LAYOUT_ERROR_CODES = [
  "ROOT_SCALE_INVALID", "ROOT_GEOMETRY_INVALID", "FRAME_INPUT_INVALID", "LAYOUT_MODE_INVALID", "LAYOUT_CONFIDENCE_LOW",
  "AUTO_LAYOUT_APPLY_FAILED", "LAYOUT_WRAP_UNSUPPORTED", "GRID_FREEFORM_FALLBACK", "PADDING_INVALID", "GAP_INVALID",
  "ALIGNMENT_INVALID", "SIZING_INVALID", "FILL_HUG_MAPPING_FAILED", "ABSOLUTE_POSITION_FAILED", "GEOMETRY_RELATIVE_CONVERSION_FAILED",
  "LAYOUT_GEOMETRY_DIVERGED", "BACKGROUND_MAPPING_FAILED", "STROKE_MAPPING_FAILED", "CORNER_RADIUS_MAPPING_FAILED", "SHADOW_MAPPING_FAILED",
  "CLIPPING_MAPPING_FAILED", "FRAME_NAME_FALLBACK", "FRAME_PARENT_APPEND_FAILED", "FRAME_RENDER_CANCELLED",
] as const;

export type LayoutErrorCode = typeof LAYOUT_ERROR_CODES[number];
