import { parseAssetReferenceDocument, validateAssetReferenceSemantics, type AssetReference, type AssetReferenceDocument, type AssetReferenceOptions, type AssetReferenceWarning, type AssetUsage, type AssetUsageType, type AssetMediaTypeHint, type AssetSourceType } from "@aio/asset-reference";
import type { NormalizedElementNode, NormalizedPageModel } from "@aio/page-model";

const MAX_REFERENCES = 1_000;
const MAX_USAGES = 5_000;
const MAX_WARNINGS = 100;
const MAX_DATA_URL_LENGTH = 100_000;

type Candidate = { nodeId: string; raw: string; sourceType: AssetSourceType; usageType: AssetUsageType; property?: string; layerIndex?: number; attributes?: AssetUsage["attributes"] };

function elements(root: NormalizedElementNode): NormalizedElementNode[] { const result: NormalizedElementNode[] = []; const visit = (node: NormalizedElementNode) => { result.push(node); for (const child of node.children) if (child.nodeType === "ELEMENT") visit(child); }; visit(root); return result; }
function scheme(raw: string): "HTTPS" | "DATA" | "BLOB" | "OTHER" { const value = raw.trim().toLowerCase(); if (value.startsWith("data:")) return "DATA"; if (value.startsWith("blob:")) return "BLOB"; if (value.startsWith("https:")) return "HTTPS"; return "OTHER"; }
function mediaHint(value: string): AssetMediaTypeHint { const lower = value.toLowerCase().split("?")[0] ?? value.toLowerCase(); if (lower.endsWith(".png")) return "PNG"; if (lower.endsWith(".jpg") || lower.endsWith(".jpeg")) return "JPEG"; if (lower.endsWith(".webp")) return "WEBP"; if (lower.endsWith(".gif")) return "GIF"; if (lower.endsWith(".avif")) return "AVIF"; if (lower.endsWith(".svg") || lower.includes("image/svg+xml")) return "SVG"; if (lower.startsWith("data:image/png")) return "PNG"; if (lower.startsWith("data:image/jpeg")) return "JPEG"; if (lower.startsWith("data:image/webp")) return "WEBP"; if (lower.startsWith("data:image/gif")) return "GIF"; if (lower.startsWith("data:image/svg+xml")) return "SVG"; return "UNKNOWN"; }
function sanitize(value: string): string { try { const url = new URL(value); url.username = ""; url.password = ""; url.hash = ""; return `${url.origin}${url.pathname}`.slice(0, 512); } catch { if (value.startsWith("data:")) return `data:${value.slice(5).split(",", 1)[0]}`; return value.slice(0, 256); } }
function dedupeKey(value: string, sourceType: AssetSourceType): string { if (value.startsWith("data:")) return `data:${mediaHint(value)}:${value.length}:${value.slice(-32)}`; return `${sourceType}:${value}`; }
function parseUrls(value: string): { urls: string[]; partial: boolean } { const urls: string[] = []; let index = 0; let partial = false; while (index < value.length) { const start = value.indexOf("url(", index); if (start < 0) break; let cursor = start + 4; while (/\s/.test(value[cursor] ?? "")) cursor += 1; const quote = value[cursor] === "\"" || value[cursor] === "'" ? value[cursor++] : undefined; const end = quote ? value.indexOf(quote, cursor) : value.indexOf(")", cursor); if (end < 0) { partial = true; break; } const raw = value.slice(cursor, end).trim(); if (raw) urls.push(raw); const close = value.indexOf(")", end); if (close < 0) { partial = true; break; } index = close + 1; } return { urls, partial }; }
function warning(code: AssetReferenceWarning["code"], nodeId: string, map: Map<string, AssetReferenceWarning>) { const item = map.get(code) ?? { code, count: 0, sampleNodeIds: [], message: code.toLowerCase().replaceAll("_", " ") }; item.count += 1; if (item.sampleNodeIds.length < 5) item.sampleNodeIds.push(nodeId); map.set(code, item); }

export async function extractAssetReferences(model: NormalizedPageModel, options: AssetReferenceOptions = {}): Promise<AssetReferenceDocument> {
  const started = Date.now(); const maxReferences = options.maxReferences ?? MAX_REFERENCES; const maxUsages = options.maxUsages ?? MAX_USAGES; const warningLimit = options.maxWarnings ?? MAX_WARNINGS;
  const candidates: Candidate[] = []; const warnings = new Map<string, AssetReferenceWarning>();
  const addCandidate = (candidate: Candidate) => { if (candidates.length < maxUsages) candidates.push(candidate); else warning("ASSET_REFERENCE_LIMIT_REACHED", candidate.nodeId, warnings); };
  for (const node of elements(model.root)) {
    const src = node.attributes.src; const current = node.attributes.currentSrc ?? src; if (current) addCandidate({ nodeId: node.id, raw: current, sourceType: "IMAGE_ELEMENT", usageType: "ELEMENT_SOURCE", attributes: { alt: node.attributes.alt, objectFit: node.style.sizing.boxSizing, objectPosition: node.attributes.objectPosition } });
    if (node.attributes.srcset) addCandidate({ nodeId: node.id, raw: node.attributes.srcset.split(",")[0]!.trim().split(/\s+/)[0]!, sourceType: "PICTURE_SOURCE", usageType: "PICTURE_CANDIDATE", property: "srcset" });
    if (node.tagName.toUpperCase() === "SVG") addCandidate({ nodeId: node.id, raw: node.inlineSvg ? `data:image/svg+xml;charset=utf-8,${encodeURIComponent(node.inlineSvg)}` : `inline-svg:${node.id}`, sourceType: "INLINE_SVG", usageType: "INLINE_SVG_CONTENT" });
    const background = node.style.visual.backgroundImageRaw; if (background) { const parsed = parseUrls(background); if (parsed.partial) warning("BACKGROUND_IMAGE_PARSE_PARTIAL", node.id, warnings); parsed.urls.forEach((raw, index) => addCandidate({ nodeId: node.id, raw, sourceType: "BACKGROUND_IMAGE", usageType: "BACKGROUND_LAYER", property: "background-image", layerIndex: index })); }
    for (const pseudo of node.style.pseudo) { const pseudoRaw = pseudo.style.backgroundImageRaw; if (!pseudoRaw) continue; const parsed = parseUrls(pseudoRaw); if (parsed.partial) warning("BACKGROUND_IMAGE_PARSE_PARTIAL", node.id, warnings); parsed.urls.forEach((raw, index) => addCandidate({ nodeId: node.id, raw, sourceType: "PSEUDO_BACKGROUND_IMAGE", usageType: pseudo.type === "BEFORE" ? "PSEUDO_BEFORE_BACKGROUND" : "PSEUDO_AFTER_BACKGROUND", property: "background-image", layerIndex: index })); }
  }
  const assets: AssetReference[] = []; const usages: AssetUsage[] = []; const byKey = new Map<string, AssetReference>();
  for (const candidate of candidates) {
    const isInline = candidate.sourceType === "INLINE_SVG"; let resolved: string | undefined; let status: AssetReference["status"] = "SUPPORTED_REFERENCE"; const currentScheme = scheme(candidate.raw); let referenceScheme = currentScheme;
    if (isInline && !candidate.raw.startsWith("data:image/svg+xml")) { referenceScheme = "OTHER"; status = "UNSUPPORTED_REFERENCE"; warning("INLINE_SVG_CONTENT_DEFERRED", candidate.nodeId, warnings); }
    else if (currentScheme === "DATA") { if (candidate.raw.length > MAX_DATA_URL_LENGTH) { status = "INVALID_REFERENCE"; warning("DATA_URL_TOO_LARGE", candidate.nodeId, warnings); } else if (!/^data:image\/(png|jpeg|webp|gif|svg\+xml);/i.test(candidate.raw)) { status = "UNSUPPORTED_REFERENCE"; warning("DATA_URL_MEDIA_TYPE_UNSUPPORTED", candidate.nodeId, warnings); } }
    else if (currentScheme === "BLOB") { status = "UNSUPPORTED_REFERENCE"; warning("BLOB_URL_UNSUPPORTED", candidate.nodeId, warnings); }
    else { try { resolved = new URL(candidate.raw, model.source.finalUrl).toString(); referenceScheme = scheme(resolved); } catch { status = "INVALID_REFERENCE"; warning("ASSET_URL_INVALID", candidate.nodeId, warnings); } if (status === "SUPPORTED_REFERENCE" && referenceScheme !== "HTTPS") { status = "BLOCKED_REFERENCE"; warning("ASSET_SCHEME_UNSUPPORTED", candidate.nodeId, warnings); } if (status === "SUPPORTED_REFERENCE" && resolved && options.securityValidator) { const result = await options.securityValidator(resolved); if (!result.safe) { status = "BLOCKED_REFERENCE"; warning("ASSET_URL_BLOCKED", candidate.nodeId, warnings); } } }
    const key = isInline ? candidate.raw : dedupeKey(resolved ?? candidate.raw, candidate.sourceType); let asset = byKey.get(key);
    if (!asset && assets.length < maxReferences) { const hint = mediaHint(resolved ?? candidate.raw); if (hint === "UNKNOWN") warning("ASSET_MEDIA_TYPE_UNKNOWN", candidate.nodeId, warnings); asset = { assetId: `asset_${String(assets.length + 1).padStart(6, "0")}`, sourceType: candidate.sourceType, mediaTypeHint: hint, reference: { original: candidate.raw, ...(resolved ? { resolved } : {}), sanitized: sanitize(resolved ?? candidate.raw), scheme: referenceScheme }, status, flags: { inline: isInline, dataUrl: currentScheme === "DATA", svg: hint === "SVG" || isInline, animatedCandidate: hint === "GIF" || hint === "WEBP", hasQuery: Boolean(resolved && new URL(resolved).search), crossOriginCandidate: Boolean(resolved && new URL(resolved).origin !== new URL(model.source.finalUrl).origin) }, deduplicationKey: key }; assets.push(asset); byKey.set(key, asset); } else if (!asset) { warning("ASSET_REFERENCE_LIMIT_REACHED", candidate.nodeId, warnings); continue; }
    if (usages.length < maxUsages) usages.push({ usageId: `usage_${String(usages.length + 1).padStart(6, "0")}`, assetId: asset.assetId, nodeId: candidate.nodeId, usageType: candidate.usageType, ...(candidate.property ? { property: candidate.property } : {}), ...(candidate.layerIndex !== undefined ? { layerIndex: candidate.layerIndex } : {}), ...(candidate.attributes ? { attributes: candidate.attributes } : {}) });
  }
  const document = parseAssetReferenceDocument({ referenceVersion: "1.0", source: { domSnapshotVersion: model.source.domSnapshotVersion, styleSnapshotVersion: model.source.styleSnapshotVersion, modelVersion: model.modelVersion, requestedUrl: model.source.requestedUrl, finalUrl: model.source.finalUrl, extractedAt: new Date().toISOString() }, assets, usages, metrics: { assetCount: assets.length, usageCount: usages.length, imageElementAssetCount: assets.filter((item) => item.sourceType === "IMAGE_ELEMENT").length, inlineSvgAssetCount: assets.filter((item) => item.sourceType === "INLINE_SVG").length, externalSvgAssetCount: assets.filter((item) => item.sourceType === "EXTERNAL_SVG").length, backgroundAssetCount: assets.filter((item) => item.sourceType === "BACKGROUND_IMAGE").length, pseudoBackgroundAssetCount: assets.filter((item) => item.sourceType === "PSEUDO_BACKGROUND_IMAGE").length, dataUrlAssetCount: assets.filter((item) => item.flags.dataUrl).length, supportedAssetCount: assets.filter((item) => item.status === "SUPPORTED_REFERENCE").length, blockedAssetCount: assets.filter((item) => item.status === "BLOCKED_REFERENCE").length, unsupportedAssetCount: assets.filter((item) => item.status === "UNSUPPORTED_REFERENCE").length, invalidAssetCount: assets.filter((item) => item.status === "INVALID_REFERENCE").length, deduplicatedUsageCount: Math.max(0, usages.length - assets.length), extractionTimeMs: Math.max(0, Date.now() - started) }, warnings: [...warnings.values()].slice(0, warningLimit) });
  validateAssetReferenceSemantics(document, model); return document;
}
