import { z } from "zod";
import { DESIGN_IR_VERSION } from "./version.js";

const finite = z.number().finite();
const color = z.object({ r: finite, g: finite, b: finite, a: finite }).strict();
const edges = <T extends z.ZodTypeAny>(value: T) => z.object({ top: value, right: value, bottom: value, left: value }).strict();
const corners = <T extends z.ZodTypeAny>(value: T) => z.object({ topLeft: value, topRight: value, bottomRight: value, bottomLeft: value }).strict();
const geometry = z.object({ x: finite, y: finite, width: finite.nonnegative(), height: finite.nonnegative(), coordinateSpace: z.enum(["DOCUMENT", "PARENT"]), source: z.enum(["MEASURED_BOUNDING_RECT", "NORMALIZED_PARENT_RELATIVE", "FALLBACK"]) }).strict();
const confidence = z.object({ layout: z.number().min(0).max(1), horizontalSizing: z.number().min(0).max(1), verticalSizing: z.number().min(0).max(1) }).strict();
const visibility = z.object({ visible: z.boolean(), renderPolicy: z.enum(["RENDER","SKIP","PLACEHOLDER","ABSOLUTE_FALLBACK","MANUAL_REVIEW"]), reasons: z.array(z.string()) }).strict();
const base = { id: z.string().regex(/^ir_\d{6}$/), name: z.string().min(1), parentId: z.string().regex(/^ir_\d{6}$/).optional(), sourceNodeId: z.string().regex(/^dom_\d{6}$/).optional(), semantic: z.object({ tagName: z.string().optional(), role: z.string().optional(), landmark: z.string().optional(), ariaLabel: z.string().optional() }).strict().optional(), geometry, visibility, confidence, renderPolicy: z.enum(["RENDER","SKIP","PLACEHOLDER","ABSOLUTE_FALLBACK","MANUAL_REVIEW"]) };
const sizingAxis = z.object({ mode: z.enum(["CONTENT","STRETCH","FIXED","RELATIVE","INTRINSIC","UNKNOWN"]), value: finite.nonnegative().optional(), confidence: z.number().min(0).max(1), constraints: z.object({ min: finite.optional(), max: finite.optional() }).strict().optional(), fallback: z.enum(["USE_MEASURED_SIZE","USE_CONTENT","USE_STRETCH","PRESERVE_RELATIVE","PRESERVE_INTRINSIC"]) }).strict();
const sizing = z.object({ horizontal: sizingAxis, vertical: sizingAxis }).strict();
const border = z.object({ width: edges(finite.nonnegative()), style: edges(z.string()), color: edges(color.optional()) }).strict();
const visual = z.object({ opacity: z.number().min(0).max(1), backgrounds: z.array(z.object({ type: z.enum(["SOLID","IMAGE","GRADIENT_RAW","UNSUPPORTED"]), color, assetBindingId: z.string().optional(), rawValue: z.string().optional() }).strict()), border, radius: corners(finite.nonnegative()), shadows: z.array(z.string()), overflow: z.enum(["VISIBLE","HIDDEN","SCROLL","AUTO","UNKNOWN"]) }).strict();
const layout = z.object({ mode: z.enum(["NONE","VERTICAL","HORIZONTAL","WRAPPED_HORIZONTAL","WRAPPED_VERTICAL","GRID_REFERENCE","FREEFORM"]), primaryAlignment: z.string(), counterAlignment: z.string(), gap: z.object({ primary: finite.optional(), cross: finite.optional() }).strict().optional(), padding: edges(finite.nonnegative()), positionedChildIds: z.array(z.string().regex(/^ir_\d{6}$/)), confidence: z.number().min(0).max(1), fallbackApplied: z.boolean() }).strict();
const node: z.ZodTypeAny = z.lazy(() => z.discriminatedUnion("nodeType", [
  z.object({ ...base, nodeType: z.literal("DOCUMENT"), viewport: z.object({ width: finite.positive(), height: finite.positive() }), documentSize: z.object({ width: finite.nonnegative(), height: finite.nonnegative() }), children: z.array(node) }).strict(),
  z.object({ ...base, nodeType: z.literal("FRAME"), layout, sizing, box: z.object({ padding: edges(finite.nonnegative()), border, radius: corners(finite.nonnegative()) }).strict(), visual, clipping: z.object({ clipsContent: z.boolean(), source: z.enum(["STYLE","FALLBACK","UNKNOWN"]) }).strict(), children: z.array(node) }).strict(),
  z.object({ ...base, nodeType: z.literal("TEXT"), text: z.string(), typography: z.object({ fontFamilies: z.array(z.string()), fontSize: finite.nonnegative().optional(), fontWeight: finite.optional(), fontStyle: z.string().optional(), lineHeight: finite.nonnegative().optional(), letterSpacing: finite.optional(), color: color.optional(), textAlign: z.string(), textDecoration: z.string().optional(), textTransform: z.string().optional(), whiteSpace: z.string().optional() }).strict(), sizing }).strict(),
  z.object({ ...base, nodeType: z.literal("IMAGE"), sizing, assetBindingId: z.string().optional(), fit: z.object({ mode: z.enum(["FILL","FIT","CROP","TILE","NONE","UNKNOWN"]), positionX: finite.optional(), positionY: finite.optional() }).strict(), opacity: z.number().min(0).max(1) }).strict(),
  z.object({ ...base, nodeType: z.literal("VECTOR"), assetBindingId: z.string().optional(), vectorStatus: z.enum(["SANITIZED_SVG_AVAILABLE","REFERENCE_ONLY","UNSUPPORTED"]), sizing }).strict(),
  z.object({ ...base, nodeType: z.literal("UNSUPPORTED"), unsupportedReason: z.enum(["IFRAME","CANVAS","VIDEO","COMPLEX_SVG","COMPLEX_GRID","LOW_CONFIDENCE_LAYOUT","INVALID_GEOMETRY","UNRESOLVED_ASSET","UNSUPPORTED_ELEMENT","OTHER"]), fallback: z.enum(["PRESERVE_BOUNDS","PLACEHOLDER","SKIP_CHILDREN","PRESERVE_CHILDREN","RASTERIZE_LATER","MANUAL_REVIEW"]), children: z.array(node).optional() }).strict()
]));
export const designIrSchema = z.object({ irVersion: z.literal(DESIGN_IR_VERSION), source: z.object({ modelVersion: z.literal("1.0"), layoutInferenceVersion: z.literal("1.0"), sizingInferenceVersion: z.literal("1.0"), assetReferenceVersion: z.literal("1.0"), assetResolutionVersion: z.literal("1.0"), requestedUrl: z.string().url(), finalUrl: z.string().url(), generatedAt: z.string().datetime() }).strict(), root: node, assetBindings: z.array(z.object({ bindingId: z.string().regex(/^binding_\d{6}$/), assetId: z.string(), resolutionStatus: z.string(), mediaType: z.string(), sha256: z.string().regex(/^[a-f0-9]{64}$/).optional(), byteLength: finite.nonnegative().optional(), usageNodeIds: z.array(z.string().regex(/^ir_\d{6}$/)), renderStrategy: z.enum(["RASTER_IMAGE","SANITIZED_SVG","PLACEHOLDER","SKIP","MANUAL_REVIEW"]) }).strict()), fallbacks: z.array(z.object({ nodeId: z.string().regex(/^ir_\d{6}$/), reason: z.string(), strategy: z.string() }).strict()), metrics: z.object({ totalNodeCount: z.number().int().nonnegative(), documentNodeCount: z.number().int().nonnegative(), frameNodeCount: z.number().int().nonnegative(), textNodeCount: z.number().int().nonnegative(), imageNodeCount: z.number().int().nonnegative(), vectorNodeCount: z.number().int().nonnegative(), unsupportedNodeCount: z.number().int().nonnegative(), renderedNodeCount: z.number().int().nonnegative(), skippedNodeCount: z.number().int().nonnegative(), placeholderNodeCount: z.number().int().nonnegative(), fallbackNodeCount: z.number().int().nonnegative(), assetBindingCount: z.number().int().nonnegative(), unresolvedAssetBindingCount: z.number().int().nonnegative(), buildTimeMs: finite.nonnegative() }).strict(), warnings: z.array(z.object({ code: z.string(), count: z.number().int().positive(), sampleNodeIds: z.array(z.string()).max(5), message: z.string() }).strict()) }).strict();
