import { z } from "zod";

const reasonCodes = ["SOURCE_DISPLAY_FLEX","SOURCE_FLEX_DIRECTION_ROW","SOURCE_FLEX_DIRECTION_COLUMN","SOURCE_FLEX_WRAP","SOURCE_DISPLAY_GRID","SOURCE_BLOCK_LIKE","HORIZONTAL_ORDERING_STRONG","VERTICAL_ORDERING_STRONG","CROSS_AXIS_ALIGNMENT_STRONG","GAP_CONSISTENT","DECLARED_GAP_MATCHES_GEOMETRY","PADDING_MATCHES_GEOMETRY","GRID_ROW_GROUPS_DETECTED","GRID_COLUMN_GROUPS_DETECTED","CHILD_SIZE_SIMILARITY_HIGH","POSITIONED_CHILD_RATIO_LOW","OVERLAP_HIGH","WRAPPING_DETECTED","INSUFFICIENT_EVIDENCE"] as const;
const conflictCodes = ["FLEX_SOURCE_GEOMETRY_MISMATCH","GRID_SOURCE_GEOMETRY_MISMATCH","DECLARED_GAP_MISMATCH","DECLARED_PADDING_MISMATCH","OVERLAP_CONFLICTS_WITH_FLOW","POSITIONED_CHILDREN_DOMINANT","WRAP_SOURCE_GEOMETRY_MISMATCH","MIXED_TEXT_ELEMENT_CONTENT","NEGATIVE_GAP_PATTERN","INSUFFICIENT_FLOW_CHILDREN","UNSTABLE_GEOMETRY_EVIDENCE"] as const;
const modes = ["LEAF","FLOW_VERTICAL","FLOW_HORIZONTAL","FLEX_ROW","FLEX_COLUMN","FLEX_ROW_WRAP","FLEX_COLUMN_WRAP","GRID","FREEFORM","UNKNOWN"] as const;
const fallback = ["USE_INFERRED_FLOW","PRESERVE_ABSOLUTE_GEOMETRY","PRESERVE_SOURCE_ORDER","RASTERIZE_UNSUPPORTED_REGION","SKIP_CONTAINER","MANUAL_REVIEW"] as const;
const finite = z.number().finite();
const numeric = z.object({ value: finite, source: z.enum(["DECLARED_STYLE","OBSERVED_MEDIAN","OBSERVED_AVERAGE"]), confidence: z.number().min(0).max(1) });
const paddingSide = z.object({ value: finite.optional(), source: z.enum(["DECLARED_STYLE","OBSERVED_GEOMETRY","UNRESOLVED"]), confidence: z.number().min(0).max(1) });
const candidate = z.object({ mode: z.enum(modes), score: z.number().min(0).max(1), evidenceCodes: z.array(z.enum(reasonCodes)), penaltyCodes: z.array(z.enum(conflictCodes)) });
const entry = z.object({ nodeId: z.string().min(1), parentId: z.string().min(1).optional(), mode: z.enum(modes), confidence: z.number().min(0).max(1), source: z.object({ display: z.string(), position: z.string() }), candidates: z.array(candidate).max(3), reasons: z.array(z.object({ code: z.enum(reasonCodes), message: z.string() })), conflicts: z.array(z.object({ code: z.enum(conflictCodes), message: z.string(), penalty: z.number().min(0).max(1) })), arrangement: z.object({ primaryAxis: z.enum(["HORIZONTAL","VERTICAL"]).optional(), wraps: z.boolean(), rowCount: z.number().int().nonnegative().optional(), columnCount: z.number().int().nonnegative().optional() }), spacing: z.object({ primaryGap: numeric.optional(), crossGap: numeric.optional(), padding: z.object({ top: paddingSide, right: paddingSide, bottom: paddingSide, left: paddingSide }).optional() }), alignment: z.object({ primary: z.enum(["START","CENTER","END","SPACE_BETWEEN","SPACE_AROUND","SPACE_EVENLY","UNKNOWN"]).optional(), counter: z.enum(["START","CENTER","END","STRETCH","BASELINE","UNKNOWN"]).optional() }), children: z.object({ flowChildIds: z.array(z.string()), positionedChildIds: z.array(z.string()), excludedChildIds: z.array(z.object({ nodeId: z.string(), reason: z.enum(["DISPLAY_NONE","HIDDEN_ATTRIBUTE","ZERO_AREA","GEOMETRY_INVALID","UNSUPPORTED_ELEMENT"]) })) }), fallback: z.enum(fallback) });
export const layoutInferenceSchema = z.object({ inferenceVersion: z.literal("1.0"), source: z.object({ modelVersion: z.literal("1.0"), evidenceVersion: z.literal("1.0"), requestedUrl: z.string(), finalUrl: z.string(), inferredAt: z.string().datetime() }), entries: z.array(entry), metrics: z.object({ entryCount: z.number().int().nonnegative(), leafCount: z.number().int().nonnegative(), flowVerticalCount: z.number().int().nonnegative(), flowHorizontalCount: z.number().int().nonnegative(), flexRowCount: z.number().int().nonnegative(), flexColumnCount: z.number().int().nonnegative(), flexWrapCount: z.number().int().nonnegative(), gridCount: z.number().int().nonnegative(), freeformCount: z.number().int().nonnegative(), unknownCount: z.number().int().nonnegative(), highConfidenceCount: z.number().int().nonnegative(), mediumConfidenceCount: z.number().int().nonnegative(), lowConfidenceCount: z.number().int().nonnegative(), conflictedEntryCount: z.number().int().nonnegative(), inferenceTimeMs: finite }), warnings: z.array(z.object({ code: z.enum(["LOW_CONFIDENCE_LAYOUT","AMBIGUOUS_LAYOUT_CANDIDATES","SOURCE_GEOMETRY_CONFLICT","COMPLEX_GRID_FALLBACK","FREEFORM_FALLBACK","UNKNOWN_LAYOUT","MIXED_CONTENT_LIMITATION"]), count: z.number().int().positive(), sampleNodeIds: z.array(z.string()).max(5), message: z.string() })) });
