import type { AssetReferenceDocument, AssetUsage } from "@aio/asset-reference";
import type { DesignIrDocument, DesignIrNode, DesignIrFrameNode, DesignIrSizing, DesignIrColor, DesignIrAssetBinding, DesignIrWarning, DesignIrFallbackRecord } from "@aio/design-ir";
import { parseDesignIr, validateDesignIrSemantics } from "@aio/design-ir";
import type { LayoutInferenceDocument } from "@aio/layout-inference";
import type { NormalizedElementNode, NormalizedNode, NormalizedPageModel, ParsedCssValue, NormalizedColor } from "@aio/page-model";
import type { ResolvedAssetDocument } from "@aio/resolved-assets";
import type { SizingInferenceDocument, AxisSizingInference } from "@aio/sizing-inference";

type Context = { model: NormalizedPageModel; layout: LayoutInferenceDocument; sizing: SizingInferenceDocument; references: AssetReferenceDocument; resolved: ResolvedAssetDocument; idMap: Map<string, string>; usagesByNode: Map<string, AssetUsage[]>; bindingByAsset: Map<string, string>; bindings: DesignIrAssetBinding[]; warnings: Map<string, DesignIrWarning>; fallbacks: DesignIrFallbackRecord[]; nextId: number };
const n = (value: unknown): number | undefined => typeof value === "number" && Number.isFinite(value) ? value : undefined;
const px = (value: ParsedCssValue<unknown> | undefined): number | undefined => { const parsed = value?.value as { type?: unknown; value?: unknown } | undefined; return parsed?.type === "PX" ? n(parsed.value) : undefined; };
const color = (value: ParsedCssValue<NormalizedColor> | undefined): DesignIrColor | undefined => {
  const parsed = value?.value;
  if (parsed?.type !== "RGBA") return undefined;
  return { r: Math.min(1, Math.max(0, parsed.r / 255)), g: Math.min(1, Math.max(0, parsed.g / 255)), b: Math.min(1, Math.max(0, parsed.b / 255)), a: Math.min(1, Math.max(0, parsed.a)) };
};
const edgeNumbers = (edge: { top: ParsedCssValue<unknown>; right: ParsedCssValue<unknown>; bottom: ParsedCssValue<unknown>; left: ParsedCssValue<unknown> }) => ({ top: px(edge.top) ?? 0, right: px(edge.right) ?? 0, bottom: px(edge.bottom) ?? 0, left: px(edge.left) ?? 0 });
const corners = (value: NormalizedElementNode["style"]["box"]["radius"]) => ({ topLeft: px(value.topLeft) ?? 0, topRight: px(value.topRight) ?? 0, bottomRight: px(value.bottomRight) ?? 0, bottomLeft: px(value.bottomLeft) ?? 0 });
const warning = (context: Context, code: DesignIrWarning["code"], nodeId: string, message: string) => { const current = context.warnings.get(code); if (current) { current.count += 1; if (current.sampleNodeIds.length < 5) current.sampleNodeIds.push(nodeId); } else context.warnings.set(code, { code, count: 1, sampleNodeIds: [nodeId], message }); };
const layoutEntry = (context: Context, id: string) => context.layout.entries.find((entry) => entry.nodeId === id);
const sizingEntry = (context: Context, id: string) => context.sizing.entries.find((entry) => entry.nodeId === id);
const nextId = (context: Context) => `ir_${String(context.nextId++).padStart(6, "0")}`;
const isTextNode = (node: NormalizedNode): node is Extract<NormalizedNode, { nodeType: "TEXT" }> => node.nodeType === "TEXT";
const mergeTextNodes = (nodes: Extract<NormalizedNode, { nodeType: "TEXT" }>[]): Extract<NormalizedNode, { nodeType: "TEXT" }> => ({ ...nodes[0]!, text: nodes.map((node) => node.text).join(""), whitespaceOnly: nodes.every((node) => node.whitespaceOnly) });
const textContent = (node: NormalizedNode): string => node.nodeType === "TEXT" ? node.text : node.children.map(textContent).join("");
const hasBoxChrome = (node: NormalizedElementNode): boolean => Object.values(edgeNumbers(node.style.box.padding)).some((value) => value > 0) || Object.values(edgeNumbers(node.style.box.borderWidth)).some((value) => value > 0) || Object.values(corners(node.style.box.radius)).some((value) => value > 0) || Boolean(node.style.visual.backgroundImageRaw || node.style.visual.boxShadowRaw || node.style.visual.filterRaw || node.style.visual.backdropFilterRaw);
const hasNonWhiteVisibleBackground = (node: NormalizedElementNode): boolean => { const value = color(node.style.visual.backgroundColor); return Boolean(value && value.a > 0 && (Math.abs(value.r - 1) > 0.01 || Math.abs(value.g - 1) > 0.01 || Math.abs(value.b - 1) > 0.01)); };
function geometry(context: Context, node: NormalizedNode, parent: NormalizedElementNode | undefined, documentRoot = false) { const rect = node.nodeType === "ELEMENT" ? node.geometry.documentRect : parent?.geometry.documentRect ?? { x: 0, y: 0, width: 0, height: 0 }; return { x: documentRoot ? 0 : parent ? rect.x - parent.geometry.documentRect.x : rect.x, y: documentRoot ? 0 : parent ? rect.y - parent.geometry.documentRect.y : rect.y, width: rect.width, height: rect.height, coordinateSpace: documentRoot ? "DOCUMENT" as const : "PARENT" as const, source: parent ? "NORMALIZED_PARENT_RELATIVE" as const : "MEASURED_BOUNDING_RECT" as const }; }
function sizingAxis(axis: AxisSizingInference, min?: number, max?: number): DesignIrSizing["horizontal"] { const value = axis.mode === "UNKNOWN" ? undefined : axis.measuredSize; const fallback = axis.mode === "RELATIVE" ? "PRESERVE_RELATIVE" : axis.mode === "INTRINSIC" ? "PRESERVE_INTRINSIC" : axis.mode === "CONTENT" ? "USE_CONTENT" : axis.mode === "STRETCH" ? "USE_STRETCH" : "USE_MEASURED_SIZE"; return { mode: axis.mode === "CONSTRAINED" ? "UNKNOWN" : axis.mode, ...(value === undefined ? {} : { value }), confidence: axis.confidence, ...(min !== undefined || max !== undefined ? { constraints: { ...(min === undefined ? {} : { min }), ...(max === undefined ? {} : { max }) } } : {}), fallback }; }
function sizingConstraint(value: { value?: number | undefined; parsed: boolean } | undefined): number | undefined { return value?.parsed ? value.value : undefined; }
function mapSizing(context: Context, nodeId: string): DesignIrSizing { const entry = sizingEntry(context, nodeId); if (!entry) return { horizontal: { mode: "UNKNOWN", confidence: 0, fallback: "USE_MEASURED_SIZE" }, vertical: { mode: "UNKNOWN", confidence: 0, fallback: "USE_MEASURED_SIZE" } }; return { horizontal: sizingAxis(entry.horizontal, sizingConstraint(entry.constraints.minWidth), sizingConstraint(entry.constraints.maxWidth)), vertical: sizingAxis(entry.vertical, sizingConstraint(entry.constraints.minHeight), sizingConstraint(entry.constraints.maxHeight)) }; }
function binding(context: Context, assetId: string, irNodeId: string): string { const existing = context.bindingByAsset.get(assetId); if (existing) { const item = context.bindings.find((candidate) => candidate.bindingId === existing); if (item && !item.usageNodeIds.includes(irNodeId)) item.usageNodeIds.push(irNodeId); return existing; } const reference = context.references.assets.find((asset) => asset.assetId === assetId); const resolved = context.resolved.assets.find((asset) => asset.assetId === assetId); const bindingId = `binding_${String(context.bindings.length + 1).padStart(6, "0")}`; const strategy = resolved?.status === "RESOLVED" ? resolved.mediaType === "IMAGE_SVG" ? "SANITIZED_SVG" : "RASTER_IMAGE" : "PLACEHOLDER"; const item: DesignIrAssetBinding = { bindingId, assetId, resolutionStatus: resolved?.status ?? reference?.status ?? "UNKNOWN", mediaType: resolved?.mediaType ?? reference?.mediaTypeHint ?? "UNKNOWN", ...(resolved?.binary?.sha256 ? { sha256: resolved.binary.sha256 } : {}), ...(resolved?.binary?.byteLength !== undefined ? { byteLength: resolved.binary.byteLength } : {}), usageNodeIds: [irNodeId], renderStrategy: strategy }; context.bindingByAsset.set(assetId, bindingId); context.bindings.push(item); return bindingId; }
function base(context: Context, node: NormalizedNode, parent: NormalizedElementNode | undefined, id: string, renderPolicy: "RENDER" | "SKIP" | "PLACEHOLDER" | "ABSOLUTE_FALLBACK" | "MANUAL_REVIEW") { const element = node.nodeType === "ELEMENT" ? node : undefined; const layout = element ? layoutEntry(context, element.id) : undefined; const sizing = element ? sizingEntry(context, element.id) : undefined; return { id, name: element?.attributes.id || element?.tagName || "Text", ...(parent ? { parentId: context.idMap.get(parent.id) } : {}), sourceNodeId: node.id, ...(element ? { semantic: { tagName: element.tagName, ...(element.semantic.role ? { role: element.semantic.role } : {}), ...(element.semantic.landmark ? { landmark: element.semantic.landmark } : {}), ...(element.semantic.ariaLabel ? { ariaLabel: element.semantic.ariaLabel } : {}) } } : {}), geometry: geometry(context, node, parent), visibility: { visible: renderPolicy === "RENDER", renderPolicy, reasons: element && element.style.visibilityEvidence.ariaHidden ? ["ARIA_HIDDEN_IS_NOT_VISUAL_SKIP"] : [] }, confidence: { layout: layout?.confidence ?? 1, horizontalSizing: sizing?.horizontal.confidence ?? 1, verticalSizing: sizing?.vertical.confidence ?? 1 }, renderPolicy }; }
function canCollapseTextOnlyElement(node: NormalizedElementNode): boolean { const display = node.style.display.value; const text = textContent(node).trim(); const tagName = node.tagName.toUpperCase(); const inlineOrTextChildren = node.children.every((child) => child.nodeType === "TEXT" || (child.nodeType === "ELEMENT" && canCollapseTextOnlyElement(child))); const plainInline = (display === "INLINE" || display === "INLINE_BLOCK") && !hasBoxChrome(node) && !hasNonWhiteVisibleBackground(node); const plainTextBlock = display === "BLOCK" && !hasBoxChrome(node) && !hasNonWhiteVisibleBackground(node) && ["A","ABBR","B","CITE","CODE","EM","H1","H2","H3","H4","H5","H6","I","P","SMALL","SPAN","STRONG"].includes(tagName); return text.length > 0 && text.length <= 240 && inlineOrTextChildren && (plainInline || plainTextBlock); }
function textNode(context: Context, node: NormalizedNode, parent: NormalizedElementNode | undefined, styleSource: NormalizedElementNode | undefined, id: string, text: string, whitespaceOnly: boolean): DesignIrNode { if (whitespaceOnly) return ({ nodeType: "UNSUPPORTED", ...base(context, node, parent, id, "SKIP"), unsupportedReason: "UNSUPPORTED_ELEMENT", fallback: "PRESERVE_BOUNDS" } as unknown as DesignIrNode); return ({ nodeType: "TEXT", ...base(context, node, parent, id, "RENDER"), text, typography: { fontFamilies: styleSource?.style.typography.fontFamily ? [styleSource.style.typography.fontFamily] : [], ...(px(styleSource?.style.typography.fontSize) === undefined ? {} : { fontSize: px(styleSource?.style.typography.fontSize) }), ...(px(styleSource?.style.typography.lineHeight) === undefined ? {} : { lineHeight: px(styleSource?.style.typography.lineHeight) }), ...(px(styleSource?.style.typography.letterSpacing) === undefined ? {} : { letterSpacing: px(styleSource?.style.typography.letterSpacing) }), ...(n(styleSource?.style.typography.fontWeight?.value) === undefined ? {} : { fontWeight: n(styleSource?.style.typography.fontWeight?.value) }), ...(color(styleSource?.style.typography.color) === undefined ? {} : { color: color(styleSource?.style.typography.color) }), textAlign: styleSource?.style.typography.textAlign ?? "UNKNOWN", ...(styleSource?.style.typography.fontStyle ? { fontStyle: styleSource.style.typography.fontStyle } : {}), ...(styleSource?.style.typography.whiteSpace ? { whiteSpace: styleSource.style.typography.whiteSpace } : {}) }, sizing: { horizontal: { mode: "CONTENT", confidence: 0.4, fallback: "USE_CONTENT" }, vertical: { mode: "CONTENT", confidence: 0.4, fallback: "USE_CONTENT" } } } as unknown as DesignIrNode); }
function visual(context: Context, node: NormalizedElementNode, irId: string) { const style = node.style; const usages = context.usagesByNode.get(node.id) ?? []; const backgrounds: DesignIrFrameNode["visual"]["backgrounds"] = []; const backgroundColor = color(style.visual.backgroundColor); if (backgroundColor && backgroundColor.a > 0) backgrounds.push({ type: "SOLID" as const, color: backgroundColor }); backgrounds.push(...usages.filter((usage) => usage.usageType === "BACKGROUND_LAYER" || usage.usageType === "PSEUDO_BEFORE_BACKGROUND" || usage.usageType === "PSEUDO_AFTER_BACKGROUND").map((usage) => ({ type: "IMAGE" as const, assetBindingId: binding(context, usage.assetId, irId), ...(usage.layerIndex === undefined ? {} : { rawValue: `layer:${usage.layerIndex}` }) }))); if (style.visual.backgroundImageRaw && !backgrounds.some((layer) => layer.type === "IMAGE")) backgrounds.push({ type: "UNSUPPORTED", rawValue: style.visual.backgroundImageRaw }); const display = style.overflow ?? ""; return { opacity: n(style.opacity?.value) ?? 1, backgrounds, border: { width: edgeNumbers(style.box.borderWidth), style: style.box.borderStyle, color: { top: color(style.box.borderColor.top), right: color(style.box.borderColor.right), bottom: color(style.box.borderColor.bottom), left: color(style.box.borderColor.left) } }, radius: corners(style.box.radius), shadows: style.visual.boxShadowRaw ? [style.visual.boxShadowRaw] : [], overflow: display === "hidden" ? "HIDDEN" as const : display === "scroll" ? "SCROLL" as const : display === "auto" ? "AUTO" as const : "VISIBLE" as const }; }
function frame(context: Context, node: NormalizedElementNode, parent: NormalizedElementNode | undefined, id: string): DesignIrFrameNode {
  const entry = layoutEntry(context, node.id);
  const cssPadding = edgeNumbers(node.style.box.padding);
  const layoutPadding = entry?.spacing.padding ? { top: entry.spacing.padding.top.value, right: entry.spacing.padding.right.value, bottom: entry.spacing.padding.bottom.value, left: entry.spacing.padding.left.value } : cssPadding;
  const excluded = node.style.visibilityEvidence.displayNone || node.style.visibilityEvidence.hiddenAttribute || node.geometry.zeroSize.area;
  const policy = excluded ? "SKIP" : entry && entry.confidence < 0.5 ? "ABSOLUTE_FALLBACK" : "RENDER";
  if (policy === "SKIP") warning(context, "NODE_SKIPPED", id, "Node retained for traceability but skipped by render policy.");
  if (policy === "ABSOLUTE_FALLBACK") {
    warning(context, "LOW_CONFIDENCE_LAYOUT_FALLBACK", id, "Low-confidence layout uses measured parent-relative geometry.");
    context.fallbacks.push({ nodeId: id, reason: "LOW_CONFIDENCE_LAYOUT", strategy: "ABSOLUTE_FALLBACK" });
  }
  const layoutMode = entry?.mode === "FLOW_VERTICAL" || entry?.mode === "FLEX_COLUMN" ? "VERTICAL" : entry?.mode === "FLOW_HORIZONTAL" || entry?.mode === "FLEX_ROW" ? "HORIZONTAL" : entry?.mode === "FLEX_ROW_WRAP" ? "WRAPPED_HORIZONTAL" : entry?.mode === "FLEX_COLUMN_WRAP" ? "WRAPPED_VERTICAL" : entry?.mode === "GRID" ? "GRID_REFERENCE" : entry?.mode === "FREEFORM" ? "FREEFORM" : "NONE";
  const children = buildChildren(context, node);
  const positioned = (entry?.children.positionedChildIds ?? []).map((sourceId) => context.idMap.get(sourceId)).filter((value): value is string => Boolean(value));
  return { nodeType: "FRAME", ...base(context, node, parent, id, policy), layout: { mode: layoutMode, primaryAlignment: entry?.alignment.primary ?? "UNKNOWN", counterAlignment: entry?.alignment.counter ?? "UNKNOWN", ...(entry?.spacing.primaryGap ? { gap: { primary: entry.spacing.primaryGap.value, ...(entry.spacing.crossGap ? { cross: entry.spacing.crossGap.value } : {}) } } : {}), padding: layoutPadding, positionedChildIds: positioned, confidence: entry?.confidence ?? 0, fallbackApplied: policy === "ABSOLUTE_FALLBACK" }, sizing: mapSizing(context, node.id), box: { padding: cssPadding, border: { width: edgeNumbers(node.style.box.borderWidth), style: node.style.box.borderStyle, color: { top: color(node.style.box.borderColor.top), right: color(node.style.box.borderColor.right), bottom: color(node.style.box.borderColor.bottom), left: color(node.style.box.borderColor.left) } }, radius: corners(node.style.box.radius) }, visual: visual(context, node, id), clipping: { clipsContent: node.style.overflow === "hidden", source: node.style.overflow === "hidden" ? "STYLE" : "UNKNOWN" }, children } as unknown as DesignIrFrameNode;
}
function buildChildren(context: Context, parent: NormalizedElementNode): DesignIrNode[] { const children: DesignIrNode[] = []; for (let index = 0; index < parent.children.length;) { const child = parent.children[index]!; if (!isTextNode(child)) { children.push(buildNode(context, child, parent)); index += 1; continue; } const group: Extract<NormalizedNode, { nodeType: "TEXT" }>[] = []; while (index < parent.children.length && isTextNode(parent.children[index]!)) group.push(parent.children[index++] as Extract<NormalizedNode, { nodeType: "TEXT" }>); children.push(buildNode(context, group.length === 1 ? group[0]! : mergeTextNodes(group), parent)); } return children; }
function buildNode(context: Context, node: NormalizedNode, parent: NormalizedElementNode | undefined): DesignIrNode { const id = context.idMap.get(node.id) ?? nextId(context); context.idMap.set(node.id, id); if (node.nodeType === "TEXT") return textNode(context, node, parent, parent, id, node.text, node.whitespaceOnly);
  if (canCollapseTextOnlyElement(node)) return textNode(context, node, parent, node, id, textContent(node), textContent(node).trim().length === 0);
  if (node.tagName === "IMG") { const usage = (context.usagesByNode.get(node.id) ?? []).find((item) => item.usageType === "ELEMENT_SOURCE"); const bindingId = usage ? binding(context, usage.assetId, id) : undefined; return ({ nodeType: "IMAGE", ...base(context, node, parent, id, bindingId ? "RENDER" : "PLACEHOLDER"), ...(bindingId ? { assetBindingId: bindingId } : {}), sizing: mapSizing(context, node.id), fit: { mode: "UNKNOWN" }, opacity: n(node.style.opacity?.value) ?? 1 } as unknown as DesignIrNode); }
  if (node.tagName === "SVG") { const usage = context.usagesByNode.get(node.id)?.[0]; const bindingId = usage ? binding(context, usage.assetId, id) : undefined; return ({ nodeType: "VECTOR", ...base(context, node, parent, id, bindingId ? "RENDER" : "PLACEHOLDER"), ...(bindingId ? { assetBindingId: bindingId } : {}), vectorStatus: bindingId ? "REFERENCE_ONLY" : "UNSUPPORTED", sizing: mapSizing(context, node.id) } as unknown as DesignIrNode); }
  if (["IFRAME", "CANVAS", "VIDEO"].includes(node.tagName)) return ({ nodeType: "UNSUPPORTED", ...base(context, node, parent, id, "PLACEHOLDER"), unsupportedReason: node.tagName === "IFRAME" ? "IFRAME" : node.tagName === "CANVAS" ? "CANVAS" : "VIDEO", fallback: "PLACEHOLDER" } as unknown as DesignIrNode);
  return frame(context, node, parent, id); }

export function buildDesignIr(input: { model: NormalizedPageModel; layout: LayoutInferenceDocument; sizing: SizingInferenceDocument; assetReferences: AssetReferenceDocument; resolvedAssets: ResolvedAssetDocument }): DesignIrDocument {
  const started = Date.now(); const context: Context = { model: input.model, layout: input.layout, sizing: input.sizing, references: input.assetReferences, resolved: input.resolvedAssets, idMap: new Map(), usagesByNode: new Map(), bindingByAsset: new Map(), bindings: [], warnings: new Map(), fallbacks: [], nextId: 1 };
  for (const usage of input.assetReferences.usages) { const list = context.usagesByNode.get(usage.nodeId) ?? []; list.push(usage); context.usagesByNode.set(usage.nodeId, list); }
  const documentId = nextId(context); const child = buildNode(context, input.model.root, undefined); const root: DesignIrDocument["root"] = { nodeType: "DOCUMENT", id: documentId, name: "Document", geometry: { x: 0, y: 0, width: input.model.viewport.width, height: input.model.document.scrollHeight, coordinateSpace: "DOCUMENT", source: "MEASURED_BOUNDING_RECT" }, visibility: { visible: true, renderPolicy: "RENDER", reasons: [] }, confidence: { layout: 1, horizontalSizing: 1, verticalSizing: 1 }, renderPolicy: "RENDER", viewport: { width: input.model.viewport.width, height: input.model.viewport.height }, documentSize: { width: input.model.document.scrollWidth, height: input.model.document.scrollHeight }, children: [child] };
  const all: DesignIrNode[] = []; const visit = (node: DesignIrNode) => { all.push(node); if ("children" in node) for (const childNode of node.children ?? []) visit(childNode); }; visit(root); const counts = { documentNodeCount: all.filter((node) => node.nodeType === "DOCUMENT").length, frameNodeCount: all.filter((node) => node.nodeType === "FRAME").length, textNodeCount: all.filter((node) => node.nodeType === "TEXT").length, imageNodeCount: all.filter((node) => node.nodeType === "IMAGE").length, vectorNodeCount: all.filter((node) => node.nodeType === "VECTOR").length, unsupportedNodeCount: all.filter((node) => node.nodeType === "UNSUPPORTED").length };
  const payload = { irVersion: "1.0" as const, source: { modelVersion: input.model.modelVersion, layoutInferenceVersion: input.layout.inferenceVersion, sizingInferenceVersion: input.sizing.inferenceVersion, assetReferenceVersion: input.assetReferences.referenceVersion, assetResolutionVersion: input.resolvedAssets.resolutionVersion, requestedUrl: input.model.source.requestedUrl, finalUrl: input.model.source.finalUrl, generatedAt: new Date().toISOString() }, root, assetBindings: context.bindings, fallbacks: context.fallbacks, metrics: { totalNodeCount: all.length, ...counts, renderedNodeCount: all.filter((node) => node.renderPolicy === "RENDER").length, skippedNodeCount: all.filter((node) => node.renderPolicy === "SKIP").length, placeholderNodeCount: all.filter((node) => node.renderPolicy === "PLACEHOLDER").length, fallbackNodeCount: context.fallbacks.length, assetBindingCount: context.bindings.length, unresolvedAssetBindingCount: context.bindings.filter((bindingItem) => bindingItem.renderStrategy === "PLACEHOLDER").length, buildTimeMs: Math.max(0, Date.now() - started) }, warnings: [...context.warnings.values()] };
  console.info(`[parser] DESIGN_IR_ROOT ${root.nodeType} child=${child.nodeType} nodes=${all.length}`);
  const result = parseDesignIr(payload); validateDesignIrSemantics(result); return result; }
