export interface RenderProgress {
  stage: "VALIDATING_IR" | "CREATING_ROOT" | "CREATING_NODES" | "APPLYING_HIERARCHY" | "COMMITTING" | "ROLLING_BACK" | "COMPLETED" | "INDEXING_ASSETS" | "DOWNLOADING_ASSETS" | "DOWNLOADING_SVG_ASSETS" | "DECODING_SVG_ASSETS" | "CREATING_IMAGES" | "CREATING_VECTOR_NODES" | "APPLYING_VECTOR_GEOMETRY" | "APPLYING_IMAGE_PAINTS" | "RESOLVING_FONTS" | "LOADING_FONTS" | "CREATING_TEXT_NODES" | "APPLYING_TYPOGRAPHY" | "CLEANING_TRANSFER_SESSION";
  completedNodes: number;
  totalNodes: number;
  currentIrNodeId?: string;
  message: string;
}
