export interface SerializableError {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
  retryable: boolean;
}

export type ErrorCode =
  | "INVALID_MESSAGE"
  | "UNSUPPORTED_MESSAGE_TYPE"
  | "HANDLER_EXECUTION_FAILED"
  | "CAPABILITY_NOT_FOUND"
  | "NOT_IMPLEMENTED"
  | "MESSAGE_TIMEOUT"
  | "CANCEL_NOT_SUPPORTED"
  | "CAPABILITY_INPUT_INVALID"
  | "CAPABILITY_VALIDATION_FAILED"
  | "CAPABILITY_EXECUTION_FAILED"
  | "CAPABILITY_CANCELLED"
  | "OPERATION_NOT_FOUND"
  | "CAPABILITY_DISABLED"
  | "CAPTURE_MODE_NOT_SUPPORTED"
  | "CAPTURE_PROVIDER_NOT_FOUND"
  | "CAPTURE_VALIDATION_FAILED"
  | "CAPTURE_FAILED"
  | "ANALYZE_REQUEST_INVALID"
  | "ANALYZE_FAILED"
  | "BROWSER_LAUNCH_FAILED"
  | "BROWSER_DISCONNECTED"
  | "BROWSER_CONTEXT_CREATION_FAILED"
  | "BROWSER_PAGE_CREATION_FAILED"
  | "BROWSER_NAVIGATION_FAILED"
  | "BROWSER_NAVIGATION_TIMEOUT"
  | "BROWSER_NAVIGATION_CANCELLED"
  | "BROWSER_RESPONSE_MISSING"
  | "BROWSER_RUNTIME_CLOSED"
  | "BROWSER_CLEANUP_FAILED"
  | "BROWSER_REQUEST_BLOCKED"
  | "BROWSER_PROTOCOL_BLOCKED"
  | "BROWSER_METHOD_BLOCKED"
  | "BROWSER_RESOURCE_TYPE_BLOCKED"
  | "BROWSER_DNS_VALIDATION_FAILED"
  | "BROWSER_IP_NOT_PUBLIC"
  | "BROWSER_REDIRECT_LIMIT_EXCEEDED"
  | "BROWSER_REDIRECT_DOWNGRADE_BLOCKED"
  | "BROWSER_REDIRECT_TARGET_BLOCKED"
  | "BROWSER_FINAL_URL_BLOCKED"
  | "BROWSER_POPUP_BLOCKED"
  | "BROWSER_DOWNLOAD_BLOCKED"
  | "BROWSER_WEBSOCKET_BLOCKED"
  | "NETWORK_REQUEST_LIMIT_EXCEEDED"
  | "TARGET_HTTP_CLIENT_ERROR"
  | "TARGET_HTTP_SERVER_ERROR"
  | "TARGET_CONTENT_TYPE_NOT_SUPPORTED"
  | "URL_INVALID"
  | "URL_TOO_LONG"
  | "URL_PROTOCOL_NOT_ALLOWED"
  | "URL_CREDENTIALS_NOT_ALLOWED"
  | "HOSTNAME_INVALID"
  | "HOSTNAME_FORBIDDEN"
  | "DNS_RESOLUTION_FAILED"
  | "DNS_NO_ADDRESS"
  | "IP_NOT_PUBLIC"
  | "METADATA_ENDPOINT_BLOCKED"
  | "REDIRECT_LIMIT_EXCEEDED"
  | "REDIRECT_PROTOCOL_DOWNGRADE"
  | "REDIRECT_TARGET_BLOCKED"
  | "SECURITY_VALIDATION_FAILED"
  | "STYLE_EXTRACTION_FAILED"
  | "STYLE_SNAPSHOT_INVALID"
  | "STYLE_SNAPSHOT_MISMATCH"
  | "STYLE_ENTRY_LIMIT_REACHED"
  | "GEOMETRY_EXTRACTION_FAILED"
  | "GEOMETRY_EVIDENCE_INVALID"
  | "GEOMETRY_SNAPSHOT_MISMATCH"
  | "SNAPSHOT_PIPELINE_UNSTABLE"
  | "NORMALIZATION_FAILED"
  | "NORMALIZED_MODEL_INVALID"
  | "NORMALIZED_MODEL_SEMANTIC_INVALID"
  | "NORMALIZATION_SOURCE_MISMATCH"
  | "IMPORT_SESSION_CREATE_FAILED"
  | "IMPORT_SESSION_INVALID"
  | "IMPORT_SESSION_SEMANTIC_INVALID"
  | "IMPORT_SESSION_LIMIT_EXCEEDED"
  | "IMPORT_SESSION_NOT_FOUND"
  | "IMPORT_SESSION_EXPIRED"
  | "IMPORT_SESSION_UNAUTHORIZED"
  | "IMPORT_ASSET_NOT_FOUND"
  | "IMPORT_ASSET_UNAVAILABLE"
  | "IMPORT_SESSION_STORE_ERROR"
  | "DESIGN_IR_BUILD_FAILED"
  | "DESIGN_IR_INVALID"
  | "DESIGN_IR_SEMANTIC_INVALID"
  | "DESIGN_IR_SOURCE_MISMATCH"
  | "DESIGN_IR_ASSET_BINDING_INVALID"
  | "DESIGN_IR_POLICY_ERROR"
  | "INTERNAL_ERROR";

export interface CapabilityWarning {
  code: string;
  message: string;
  severity: "LOW" | "MEDIUM" | "HIGH";
  nodeId?: string;
  sourceSelector?: string;
  recoverable: boolean;
}

export interface CapabilityFailure {
  code: string;
  message: string;
  nodeId?: string;
  sourceSelector?: string;
  cause?: string;
}
