import { z } from "zod";
const modes = ["CONTENT","STRETCH","FIXED","RELATIVE","INTRINSIC","CONSTRAINED","UNKNOWN"] as const;
const reasons = ["CSS_SIZE_FIXED_PX","CSS_SIZE_AUTO","CSS_SIZE_RELATIVE","CSS_MIN_CONSTRAINT","CSS_MAX_CONSTRAINT","CSS_ASPECT_RATIO","PARENT_CONTENT_MATCH","CONTENT_BOUNDS_MATCH","BLOCK_AUTO_WIDTH_STRETCH","BLOCK_AUTO_HEIGHT_CONTENT","FLEX_GROW_POSITIVE","FLEX_BASIS_ZERO","FLEX_COUNTER_AXIS_STRETCH","GRID_TRACK_STRETCH","INLINE_CONTENT_SIZING","INLINE_BLOCK_CONTENT_SIZING","REPLACED_ELEMENT_INTRINSIC","ABSOLUTE_INSET_STRETCH","MEASURED_SIZE_AVAILABLE","INSUFFICIENT_SIZING_EVIDENCE"] as const;
const conflicts = ["CSS_GEOMETRY_SIZE_MISMATCH","PARENT_SIZE_RELATION_MISMATCH","CONTENT_SIZE_RELATION_MISMATCH","FIXED_AND_STRETCH_CONFLICT","CONTENT_AND_STRETCH_CONFLICT","RELATIVE_SOURCE_LOST_IN_COMPUTED_STYLE","MIN_MAX_CONSTRAINT_CONFLICT","ASPECT_RATIO_MISMATCH","TRANSFORM_AFFECTS_MEASURED_SIZE","OVERFLOW_AFFECTS_CONTENT_SIZE","TEXT_GEOMETRY_UNAVAILABLE","GRID_SIZING_AMBIGUOUS","ABSOLUTE_SIZING_AMBIGUOUS"] as const;
const finite = z.number().finite();
const candidate = z.object({ mode: z.enum(modes), score: z.number().min(0).max(1), evidenceCodes: z.array(z.enum(reasons)), penaltyCodes: z.array(z.enum(conflicts)) });
const axis = z.object({ mode: z.enum(modes), confidence: z.number().min(0).max(1), measuredSize: finite.nonnegative(), candidates: z.array(candidate).max(3), sourceValue: z.object({ raw: z.string(), parsedKind: z.enum(["PX","PERCENT","AUTO","KEYWORD","RELATIVE_UNIT","CALC","UNPARSED"]) }), parentRelation: z.object({ parentContentSize: finite.nonnegative(), childMeasuredSize: finite.nonnegative(), ratio: finite.nonnegative().optional(), remainingSpace: finite.optional(), approximatelyMatchesParent: z.boolean() }).optional(), contentRelation: z.object({ contentBoundsSize: finite.nonnegative().optional(), measuredSize: finite.nonnegative(), delta: finite.optional(), ratio: finite.nonnegative().optional(), closelyFitsContent: z.boolean() }).optional() });
const constraint = z.object({ raw: z.string(), value: finite.optional(), parsed: z.boolean() });
export const sizingInferenceSchema = z.object({ inferenceVersion: z.literal("1.0"), source: z.object({ modelVersion: z.literal("1.0"), layoutEvidenceVersion: z.literal("1.0"), layoutInferenceVersion: z.literal("1.0"), requestedUrl: z.string(), finalUrl: z.string(), inferredAt: z.string().datetime() }), entries: z.array(z.object({ nodeId: z.string(), parentId: z.string().optional(), horizontal: axis, vertical: axis, aspectRatio: z.object({ value: finite.optional(), raw: z.string(), parsed: z.boolean(), source: z.enum(["DECLARED_STYLE","GEOMETRY_OBSERVED","UNRESOLVED"]), confidence: z.number().min(0).max(1) }).optional(), constraints: z.object({ minWidth: constraint.optional(), maxWidth: constraint.optional(), minHeight: constraint.optional(), maxHeight: constraint.optional() }), reasons: z.array(z.object({ code: z.enum(reasons), message: z.string() })), conflicts: z.array(z.object({ code: z.enum(conflicts), message: z.string(), penalty: z.number().min(0).max(1) })), fallback: z.enum(["USE_MEASURED_FIXED_SIZE","USE_PARENT_STRETCH","USE_CONTENT_SIZE","PRESERVE_RELATIVE_SOURCE","PRESERVE_INTRINSIC_SIZE","PRESERVE_ABSOLUTE_GEOMETRY","MANUAL_REVIEW"]) })), metrics: z.object({ entryCount: z.number().int().nonnegative(), horizontalContentCount: z.number().int().nonnegative(), horizontalStretchCount: z.number().int().nonnegative(), horizontalFixedCount: z.number().int().nonnegative(), horizontalRelativeCount: z.number().int().nonnegative(), horizontalIntrinsicCount: z.number().int().nonnegative(), horizontalUnknownCount: z.number().int().nonnegative(), verticalContentCount: z.number().int().nonnegative(), verticalStretchCount: z.number().int().nonnegative(), verticalFixedCount: z.number().int().nonnegative(), verticalRelativeCount: z.number().int().nonnegative(), verticalIntrinsicCount: z.number().int().nonnegative(), verticalUnknownCount: z.number().int().nonnegative(), constrainedEntryCount: z.number().int().nonnegative(), conflictedEntryCount: z.number().int().nonnegative(), lowConfidenceEntryCount: z.number().int().nonnegative(), inferenceTimeMs: finite }), warnings: z.array(z.object({ code: z.enum(["LOW_CONFIDENCE_SIZING","AMBIGUOUS_SIZING_CANDIDATES","CSS_GEOMETRY_CONFLICT","RELATIVE_SOURCE_UNRESOLVED","INTRINSIC_SIZE_UNRESOLVED","TEXT_SIZE_LIMITATION","GRID_SIZING_LIMITATION","ABSOLUTE_SIZING_LIMITATION"]), count: z.number().int().positive(), sampleNodeIds: z.array(z.string()).max(5), message: z.string() })) });
