import type { DesignIrDocument } from "@aio/design-ir";

const edge = { top: 8, right: 8, bottom: 8, left: 8 };
const corner = { topLeft: 4, topRight: 4, bottomRight: 4, bottomLeft: 4 };
const border = { width: edge, style: { top: "none", right: "none", bottom: "none", left: "none" }, color: { top: undefined, right: undefined, bottom: undefined, left: undefined } };
const base = (id: string, nodeType: "DOCUMENT" | "FRAME" | "TEXT", name: string, parentId?: string) => ({ id, nodeType, name, ...(parentId ? { parentId } : {}), sourceNodeId: id.replace("ir_", "dom_"), geometry: { x: 0, y: 0, width: 100, height: 50, coordinateSpace: "PARENT" as const, source: "NORMALIZED_PARENT_RELATIVE" as const }, visibility: { visible: true, renderPolicy: "RENDER" as const, reasons: [] }, confidence: { layout: 0.9, horizontalSizing: 0.8, verticalSizing: 0.8 }, renderPolicy: "RENDER" as const });
const sizing = { horizontal: { mode: "STRETCH" as const, confidence: 0.8, fallback: "USE_STRETCH" as const }, vertical: { mode: "CONTENT" as const, confidence: 0.8, fallback: "USE_CONTENT" as const } };

export function createDocumentForRendererTest(): DesignIrDocument {
  const text = { ...base("ir_000003", "TEXT", "Hello", "ir_000002"), text: "Hello", typography: { fontFamilies: ["Inter"], fontSize: 16, fontWeight: 400, textAlign: "LEFT" }, sizing };
  const frame = { ...base("ir_000002", "FRAME", "Content", "ir_000001"), layout: { mode: "VERTICAL" as const, primaryAlignment: "START", counterAlignment: "STRETCH", padding: edge, positionedChildIds: [], confidence: 0.9, fallbackApplied: false }, sizing, box: { padding: edge, border, radius: corner }, visual: { opacity: 1, backgrounds: [], border, radius: corner, shadows: [], overflow: "VISIBLE" as const }, clipping: { clipsContent: false, source: "FALLBACK" as const }, children: [text] };
  return { irVersion: "1.0", source: { modelVersion: "1.0", layoutInferenceVersion: "1.0", sizingInferenceVersion: "1.0", assetReferenceVersion: "1.0", assetResolutionVersion: "1.0", requestedUrl: "https://example.test", finalUrl: "https://example.test", generatedAt: new Date().toISOString() }, root: { ...base("ir_000001", "DOCUMENT", "Imported Website"), geometry: { x: 0, y: 0, width: 400, height: 300, coordinateSpace: "DOCUMENT", source: "FALLBACK" }, viewport: { width: 400, height: 300 }, documentSize: { width: 400, height: 300 }, children: [frame] } as DesignIrDocument["root"], assetBindings: [], fallbacks: [], metrics: { totalNodeCount: 3, documentNodeCount: 1, frameNodeCount: 1, textNodeCount: 1, imageNodeCount: 0, vectorNodeCount: 0, unsupportedNodeCount: 0, renderedNodeCount: 3, skippedNodeCount: 0, placeholderNodeCount: 0, fallbackNodeCount: 0, assetBindingCount: 0, unresolvedAssetBindingCount: 0, buildTimeMs: 0 }, warnings: [] };
}
