import { createHash } from "node:crypto";
import { XMLParser } from "fast-xml-parser";
import { parseResolvedAssetDocument, validateResolvedAssetSemantics, type ResolvedAsset, type ResolvedAssetDocument, type ResolvedAssetOptions, type ResolvedAssetStatus, type ResolvedAssetWarning, type ResolvedMediaType } from "@aio/resolved-assets";
import type { AssetReference, AssetReferenceDocument } from "@aio/asset-reference";

const DEFAULTS = { maxBytes: 5 * 1024 * 1024, maxTotalBytes: 20 * 1024 * 1024, maxConcurrency: 4, maxRedirects: 5, timeoutMs: 10_000, maxImageWidth: 16_384, maxImageHeight: 16_384, maxImagePixels: 100_000_000, signal: new AbortController().signal, fetcher: fetch };
type Inspection = { detected: ResolvedMediaType; width?: number | undefined; height?: number | undefined; animated?: boolean | undefined; signatureMatched: boolean; svgSanitized?: boolean | undefined };
export interface RuntimeResolvedAsset {
  asset: ResolvedAsset;
  bytes?: Uint8Array;
}
type RuntimeResult = RuntimeResolvedAsset & { hash?: string };

function sanitized(value: string): string { try { const url = new URL(value); url.username = ""; url.password = ""; url.hash = ""; return `${url.origin}${url.pathname}`.slice(0, 512); } catch { return value.startsWith("data:") ? `data:${value.slice(5).split(",", 1)[0]}` : value.slice(0, 256); } }
function warning(code: ResolvedAssetWarning["code"], assetId: string, warnings: Map<string, ResolvedAssetWarning>) { const item = warnings.get(code) ?? { code, count: 0, sampleAssetIds: [], message: code.toLowerCase().replaceAll("_", " ") }; item.count += 1; if (item.sampleAssetIds.length < 5) item.sampleAssetIds.push(assetId); warnings.set(code, item); }
function statusAsset(reference: AssetReference, status: ResolvedAssetStatus, warnings: string[] = []): ResolvedAsset { return { assetId: reference.assetId, status, mediaType: "UNKNOWN", source: { sanitizedUrl: reference.reference.sanitized, redirectCount: 0 }, inspection: { signatureMatched: false }, warnings }; }
function mediaTypeFromHeader(value: string | null): ResolvedMediaType { const lower = (value ?? "").toLowerCase().split(";", 1)[0]; return lower === "image/png" ? "IMAGE_PNG" : lower === "image/jpeg" ? "IMAGE_JPEG" : lower === "image/webp" ? "IMAGE_WEBP" : lower === "image/gif" ? "IMAGE_GIF" : lower === "image/avif" ? "IMAGE_AVIF" : lower === "image/svg+xml" ? "IMAGE_SVG" : "UNKNOWN"; }
function bytesEqual(bytes: Uint8Array, values: number[]): boolean { return values.every((value, index) => bytes[index] === value); }
function inspectBinary(bytes: Uint8Array, contentType: string | null): Inspection {
  if (bytesEqual(bytes, [0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])) return { detected: "IMAGE_PNG", ...pngSize(bytes), signatureMatched: true };
  if (bytesEqual(bytes, [0xff,0xd8,0xff])) return { detected: "IMAGE_JPEG", ...jpegSize(bytes), signatureMatched: true };
  if (bytesEqual(bytes, [0x47,0x49,0x46,0x38,0x37,0x61]) || bytesEqual(bytes, [0x47,0x49,0x46,0x38,0x39,0x61])) return { detected: "IMAGE_GIF", width: le16(bytes, 6), height: le16(bytes, 8), animated: true, signatureMatched: true };
  if (bytesEqual(bytes, [0x52,0x49,0x46,0x46]) && String.fromCharCode(...bytes.slice(8, 12)) === "WEBP") return { detected: "IMAGE_WEBP", ...webpSize(bytes), signatureMatched: true };
  if (isSvg(bytes)) return { detected: "IMAGE_SVG", signatureMatched: true, svgSanitized: sanitizeSvg(new TextDecoder().decode(bytes)) };
  return { detected: mediaTypeFromHeader(contentType), signatureMatched: false };
}
function le16(bytes: Uint8Array, offset: number): number | undefined { return bytes.length >= offset + 2 ? bytes[offset]! | (bytes[offset + 1]! << 8) : undefined; }
function be16(bytes: Uint8Array, offset: number): number | undefined { return bytes.length >= offset + 2 ? (bytes[offset]! << 8) | bytes[offset + 1]! : undefined; }
function be32(bytes: Uint8Array, offset: number): number | undefined { return bytes.length >= offset + 4 ? bytes[offset]! * 0x1000000 + bytes[offset + 1]! * 0x10000 + bytes[offset + 2]! * 0x100 + bytes[offset + 3]! : undefined; }
function pngSize(bytes: Uint8Array): { width?: number | undefined; height?: number | undefined } { return { width: be32(bytes, 16), height: be32(bytes, 20) }; }
function jpegSize(bytes: Uint8Array): { width?: number | undefined; height?: number | undefined } { let offset = 2; while (offset + 9 < bytes.length) { if (bytes[offset] !== 0xff) { offset += 1; continue; } const marker = bytes[offset + 1]!; const length = be16(bytes, offset + 2) ?? 0; if ((marker >= 0xc0 && marker <= 0xc3) || (marker >= 0xc5 && marker <= 0xc7) || (marker >= 0xc9 && marker <= 0xcb) || (marker >= 0xcd && marker <= 0xcf)) return { height: be16(bytes, offset + 5), width: be16(bytes, offset + 7) }; if (length < 2) break; offset += length + 2; } return {}; }
function webpSize(bytes: Uint8Array): { width?: number | undefined; height?: number | undefined } { const chunk = String.fromCharCode(...bytes.slice(12, 16)); if (chunk === "VP8X" && bytes.length >= 30) return { width: 1 + bytes[24]! + (bytes[25]! << 8) + (bytes[26]! << 16), height: 1 + bytes[27]! + (bytes[28]! << 8) + (bytes[29]! << 16) }; return {}; }
function isSvg(bytes: Uint8Array): boolean { const text = new TextDecoder().decode(bytes.slice(0, Math.min(bytes.length, 4096))).replace(/^\uFEFF/, "").trimStart(); return text.startsWith("<svg") || (text.startsWith("<?xml") && text.includes("<svg")); }
function sanitizeSvg(source: string): boolean {
  if (/<!DOCTYPE|<!ENTITY/i.test(source)) return false;
  try {
    const parsed = new XMLParser({ ignoreAttributes: false, processEntities: false, allowBooleanAttributes: false }).parse(source);
    const root = parsed?.svg;
    if (!root || typeof root !== "object") return false;
    const serialized = JSON.stringify(parsed);
    if (/<(script|foreignObject|iframe|object|embed|audio|video)\b/i.test(source) || /\bon[a-z]+\s*=/i.test(source) || /javascript:/i.test(source) || /(?:https?:|data:).*?(?:href|url\()/i.test(source)) return false;
    return Boolean(serialized);
  } catch { return false; }
}
function compatible(reference: AssetReference, detected: ResolvedMediaType): boolean { const hint = reference.mediaTypeHint; if (hint === "UNKNOWN") return detected !== "UNKNOWN"; if (hint === "SVG") return detected === "IMAGE_SVG"; return `IMAGE_${hint}` === detected; }
function decodeDataUrl(value: string): { bytes?: Uint8Array; contentType: string | null } { const match = /^data:([^;,]*)(;base64)?,(.*)$/is.exec(value); if (!match) return { contentType: null }; const contentType = match[1] || null; try { const body = match[2] ? Buffer.from(match[3]!, "base64") : Buffer.from(decodeURIComponent(match[3]!)); return { bytes: new Uint8Array(body), contentType }; } catch { return { contentType }; } }
async function readBody(response: Response, maxBytes: number, budget: { used: number; max: number }, signal?: AbortSignal): Promise<{ bytes?: Uint8Array; exceeded: boolean; totalExceeded: boolean }> {
  if (response.body === null) return { bytes: new Uint8Array(), exceeded: false, totalExceeded: false }; const reader = response.body.getReader(); const chunks: Uint8Array[] = []; let size = 0;
  try { while (true) { if (signal?.aborted) throw new DOMException("Aborted", "AbortError"); const item = await reader.read(); if (item.done) break; size += item.value.byteLength; if (size > maxBytes) { await reader.cancel(); return { exceeded: true, totalExceeded: false }; } if (budget.used + size > budget.max) { await reader.cancel(); return { exceeded: false, totalExceeded: true }; } chunks.push(item.value); } budget.used += size; const result = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { result.set(chunk, offset); offset += chunk.byteLength; } return { bytes: result, exceeded: false, totalExceeded: false }; } finally { reader.releaseLock(); }
}
// Kept temporarily as a compatibility reference while the explicit redirect loop below is exercised.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
async function resolveOneLegacy(reference: AssetReference, options: Required<ResolvedAssetOptions>, budget: { used: number; max: number }, warnings: Map<string, ResolvedAssetWarning>): Promise<RuntimeResult> {
  if (reference.status !== "SUPPORTED_REFERENCE") return { asset: statusAsset(reference, "SKIPPED_UNSUPPORTED_REFERENCE") };
  if (reference.reference.scheme === "DATA") { const decoded = decodeDataUrl(reference.reference.original); if (!decoded.bytes) { warning("ASSET_FETCH_FAILED", reference.assetId, warnings); return { asset: statusAsset(reference, "FETCH_FAILED", ["invalid data URL"]) }; } const inspection = inspectBinary(decoded.bytes, decoded.contentType); return finalize(reference, decoded.bytes, decoded.contentType, inspection, 0, options, warnings); }
  let url = reference.reference.resolved ?? reference.reference.original; let redirects = 0; let response: Response | undefined; let declared: string | null = null;
  while (true) { if (options.signal.aborted) throw new DOMException("Aborted", "AbortError"); if (!(await options.securityValidator(url)).safe) { warning("ASSET_REDIRECT_BLOCKED", reference.assetId, warnings); return { asset: statusAsset(reference, "BLOCKED_SECURITY_POLICY", ["security policy blocked asset URL"]) }; } const controller = new AbortController(); const abort = () => controller.abort(); options.signal.addEventListener("abort", abort, { once: true }); const timer = setTimeout(() => controller.abort(), options.timeoutMs); try { response = await options.fetcher(url, { method: "GET", redirect: "manual", signal: controller.signal, headers: { Accept: "image/png,image/jpeg,image/webp,image/gif,image/avif,image/svg+xml", "User-Agent": "AIO-Asset-Resolver/1.0" } }); } catch (error) { clearTimeout(timer); options.signal.removeEventListener("abort", abort); if (options.signal.aborted) throw error; warning("ASSET_FETCH_TIMEOUT", reference.assetId, warnings); return { asset: statusAsset(reference, "FETCH_TIMEOUT", ["asset fetch timed out"]) }; } clearTimeout(timer); options.signal.removeEventListener("abort", abort); declared = response.headers.get("content-type"); if (response.status >= 300 && response.status < 400) { const location = response.headers.get("location"); if (!location) return { asset: statusAsset(reference, "FETCH_FAILED", ["redirect location missing"]) }; redirects += 1; if (redirects > options.maxRedirects) { warning("ASSET_REDIRECT_BLOCKED", reference.assetId, warnings); return { asset: statusAsset(reference, "REDIRECT_LIMIT_REACHED", ["asset redirect limit reached"]) }; } try { url = new URL(location, url).toString(); } catch { return { asset: statusAsset(reference, "FETCH_FAILED", ["invalid redirect location"]) }; continue; } break; } }
  if (!response || response.status < 200 || response.status >= 300) return { asset: statusAsset(reference, "HTTP_STATUS_REJECTED", [`http status ${response?.status ?? 0}`]) }; const contentLengthValue = response.headers.get("content-length"); const contentLength = contentLengthValue ? Number(contentLengthValue) : undefined; if (contentLength !== undefined && (!Number.isFinite(contentLength) || contentLength > options.maxBytes || budget.used + contentLength > budget.max)) return { asset: statusAsset(reference, contentLength > options.maxBytes ? "CONTENT_LENGTH_EXCEEDED" : "TOTAL_BUDGET_EXCEEDED", ["asset byte limit exceeded"]) }; const body = await readBody(response, options.maxBytes, budget, options.signal); if (body.totalExceeded) { warning("TOTAL_ASSET_BUDGET_REACHED", reference.assetId, warnings); return { asset: statusAsset(reference, "TOTAL_BUDGET_EXCEEDED", ["total asset byte budget reached"]) }; } if (body.exceeded || !body.bytes) { warning("ASSET_TOO_LARGE", reference.assetId, warnings); return { asset: statusAsset(reference, "STREAM_SIZE_EXCEEDED", ["asset stream byte limit exceeded"]) }; } const inspection = inspectBinary(body.bytes, declared); return finalize(reference, body.bytes, declared, inspection, redirects, options, warnings, url);
}
function finalize(reference: AssetReference, bytes: Uint8Array, declared: string | null, inspection: Inspection, redirects: number, options: Required<ResolvedAssetOptions>, warnings: Map<string, ResolvedAssetWarning>, finalUrl = reference.reference.resolved ?? reference.reference.original): RuntimeResult {
  const detectedHeader = mediaTypeFromHeader(declared); const media = inspection.detected; if (!inspection.signatureMatched || media === "UNKNOWN") { warning("FILE_SIGNATURE_INVALID", reference.assetId, warnings); return { asset: { ...statusAsset(reference, "SIGNATURE_INVALID"), source: { sanitizedUrl: reference.reference.sanitized, finalSanitizedUrl: sanitized(finalUrl), redirectCount: redirects }, inspection: { declaredContentType: declared ?? undefined, detectedMediaType: media, signatureMatched: false, contentLengthHeader: bytes.byteLength } } }; }
  if (!compatible(reference, media) || (detectedHeader !== "UNKNOWN" && detectedHeader !== media)) { warning("CONTENT_TYPE_MISMATCH", reference.assetId, warnings); return { asset: { ...statusAsset(reference, "MIME_MISMATCH"), mediaType: media, source: { sanitizedUrl: reference.reference.sanitized, finalSanitizedUrl: sanitized(finalUrl), redirectCount: redirects }, inspection: { declaredContentType: declared ?? undefined, detectedMediaType: media, signatureMatched: true, contentLengthHeader: bytes.byteLength } } }; }
  if (media === "IMAGE_SVG" && inspection.svgSanitized !== true) { warning("SVG_SANITIZATION_FAILED", reference.assetId, warnings); return { asset: { ...statusAsset(reference, "SVG_SANITIZATION_FAILED"), mediaType: media, source: { sanitizedUrl: reference.reference.sanitized, finalSanitizedUrl: sanitized(finalUrl), redirectCount: redirects }, inspection: { declaredContentType: declared ?? undefined, detectedMediaType: media, signatureMatched: true, contentLengthHeader: bytes.byteLength } } }; }
  if (inspection.width !== undefined && inspection.height !== undefined && (inspection.width > options.maxImageWidth || inspection.height > options.maxImageHeight || inspection.width * inspection.height > options.maxImagePixels)) { warning("IMAGE_DIMENSION_LIMIT_EXCEEDED", reference.assetId, warnings); return { asset: { ...statusAsset(reference, "IMAGE_DIMENSION_LIMIT_EXCEEDED"), mediaType: media, source: { sanitizedUrl: reference.reference.sanitized, finalSanitizedUrl: sanitized(finalUrl), redirectCount: redirects }, inspection: { declaredContentType: declared ?? undefined, detectedMediaType: media, signatureMatched: true, contentLengthHeader: bytes.byteLength } } }; }
  const sha256 = createHash("sha256").update(bytes).digest("hex"); return { hash: sha256, bytes, asset: { assetId: reference.assetId, status: "RESOLVED", mediaType: media, binary: { byteLength: bytes.byteLength, sha256 }, ...(inspection.width !== undefined || inspection.height !== undefined ? { metadata: { width: inspection.width, height: inspection.height, aspectRatio: inspection.width && inspection.height ? inspection.width / inspection.height : undefined, animatedCandidate: inspection.animated } } : {}), source: { sanitizedUrl: reference.reference.sanitized, finalSanitizedUrl: sanitized(finalUrl), redirectCount: redirects }, inspection: { declaredContentType: declared ?? undefined, detectedMediaType: media, signatureMatched: true, contentLengthHeader: bytes.byteLength }, warnings: [] } };
}
async function resolveOne(reference: AssetReference, options: Required<ResolvedAssetOptions>, budget: { used: number; max: number }, warnings: Map<string, ResolvedAssetWarning>): Promise<RuntimeResult> {
  if (reference.status !== "SUPPORTED_REFERENCE") return { asset: statusAsset(reference, "SKIPPED_UNSUPPORTED_REFERENCE") };
  if (reference.reference.scheme === "DATA") { const decoded = decodeDataUrl(reference.reference.original); if (!decoded.bytes) return { asset: statusAsset(reference, "FETCH_FAILED", ["invalid data URL"]) }; return finalize(reference, decoded.bytes, decoded.contentType, inspectBinary(decoded.bytes, decoded.contentType), 0, options, warnings); }
  let url = reference.reference.resolved ?? reference.reference.original;
  for (let redirectCount = 0; redirectCount <= options.maxRedirects; redirectCount += 1) {
    if (options.signal.aborted) throw new DOMException("Aborted", "AbortError");
    if (!(await options.securityValidator(url)).safe) return { asset: statusAsset(reference, "BLOCKED_SECURITY_POLICY", ["security policy blocked asset URL"]) };
    const controller = new AbortController(); const abort = () => controller.abort(); options.signal.addEventListener("abort", abort, { once: true }); const timer = setTimeout(() => controller.abort(), options.timeoutMs);
    let response: Response;
    try { response = await options.fetcher(url, { method: "GET", redirect: "manual", signal: controller.signal, headers: { Accept: "image/png,image/jpeg,image/webp,image/gif,image/avif,image/svg+xml", "User-Agent": "AIO-Asset-Resolver/1.0" } }); } catch (error) { if (options.signal.aborted) throw error; clearTimeout(timer); options.signal.removeEventListener("abort", abort); return { asset: statusAsset(reference, "FETCH_TIMEOUT", ["asset fetch timed out"]) }; }
    clearTimeout(timer); options.signal.removeEventListener("abort", abort);
    if (response.status >= 300 && response.status < 400) { const location = response.headers.get("location"); if (!location) return { asset: statusAsset(reference, "FETCH_FAILED", ["redirect location missing"]) }; if (redirectCount === options.maxRedirects) return { asset: statusAsset(reference, "REDIRECT_LIMIT_REACHED", ["asset redirect limit reached"]) }; try { url = new URL(location, url).toString(); } catch { return { asset: statusAsset(reference, "FETCH_FAILED", ["invalid redirect location"]) }; } continue; }
    if (response.status < 200 || response.status >= 300) return { asset: statusAsset(reference, "HTTP_STATUS_REJECTED", [`http status ${response.status}`]) };
    const declared = response.headers.get("content-type"); const contentLengthValue = response.headers.get("content-length"); const contentLength = contentLengthValue ? Number(contentLengthValue) : undefined;
    if (contentLength !== undefined && (!Number.isFinite(contentLength) || contentLength > options.maxBytes || budget.used + contentLength > budget.max)) return { asset: statusAsset(reference, contentLength > options.maxBytes ? "CONTENT_LENGTH_EXCEEDED" : "TOTAL_BUDGET_EXCEEDED", ["asset byte limit exceeded"]) };
    const body = await readBody(response, options.maxBytes, budget, options.signal); if (body.totalExceeded) return { asset: statusAsset(reference, "TOTAL_BUDGET_EXCEEDED", ["total asset byte budget reached"]) }; if (body.exceeded || !body.bytes) return { asset: statusAsset(reference, "STREAM_SIZE_EXCEEDED", ["asset stream byte limit exceeded"]) };
    return finalize(reference, body.bytes, declared, inspectBinary(body.bytes, declared), redirectCount, options, warnings, url);
  }
  return { asset: statusAsset(reference, "REDIRECT_LIMIT_REACHED", ["asset redirect limit reached"]) };
}
export async function resolveAssetsWithRuntime(references: AssetReferenceDocument, options: ResolvedAssetOptions): Promise<{ document: ResolvedAssetDocument; runtimeAssets: RuntimeResolvedAsset[] }> {
  const started = Date.now(); const merged = { ...DEFAULTS, ...options }; const warnings = new Map<string, ResolvedAssetWarning>(); const budget = { used: 0, max: merged.maxTotalBytes }; const results: RuntimeResult[] = []; let cursor = 0;
  const worker = async () => { while (true) { const index = cursor++; if (index >= references.assets.length) return; results[index] = await resolveOne(references.assets[index]!, merged, budget, warnings); } }; await Promise.all(Array.from({ length: Math.min(merged.maxConcurrency, references.assets.length || 1) }, worker));
  const assets = results.map((item) => item.asset); const hashes = new Set<string>(); let duplicateBinaryCount = 0; for (const result of results) if (result.hash) { if (hashes.has(result.hash)) { duplicateBinaryCount += 1; warning("DUPLICATE_BINARY_DETECTED", result.asset.assetId, warnings); } hashes.add(result.hash); }
  const countMedia = (media: ResolvedMediaType) => assets.filter((asset) => asset.mediaType === media && asset.status === "RESOLVED").length; const resolvedCount = assets.filter((asset) => asset.status === "RESOLVED").length; const skippedCount = assets.filter((asset) => asset.status === "SKIPPED_UNSUPPORTED_REFERENCE").length; const blockedCount = assets.filter((asset) => asset.status === "BLOCKED_SECURITY_POLICY").length;
  const document = parseResolvedAssetDocument({ resolutionVersion: "1.0", source: { assetReferenceVersion: references.referenceVersion, requestedUrl: references.source.requestedUrl, finalUrl: references.source.finalUrl, resolvedAt: new Date().toISOString() }, assets, metrics: { totalReferenceCount: references.assets.length, attemptedCount: assets.length, resolvedCount, blockedCount, failedCount: assets.length - resolvedCount - blockedCount - skippedCount, skippedCount, totalDownloadedBytes: assets.reduce((sum, asset) => sum + (asset.binary?.byteLength ?? 0), 0), uniqueBinaryCount: hashes.size, duplicateBinaryCount, pngCount: countMedia("IMAGE_PNG"), jpegCount: countMedia("IMAGE_JPEG"), webpCount: countMedia("IMAGE_WEBP"), gifCount: countMedia("IMAGE_GIF"), avifCount: countMedia("IMAGE_AVIF"), svgCount: countMedia("IMAGE_SVG"), sanitizedSvgCount: assets.filter((asset) => asset.status === "RESOLVED" && asset.mediaType === "IMAGE_SVG").length, rejectedSvgCount: assets.filter((asset) => asset.status === "SVG_INVALID" || asset.status === "SVG_SANITIZATION_FAILED").length, resolutionTimeMs: Math.max(0, Date.now() - started) }, warnings: [...warnings.values()] }); validateResolvedAssetSemantics(document, references); return { document, runtimeAssets: results.flatMap((result) => result.asset.status === "RESOLVED" && result.bytes ? [{ asset: result.asset, bytes: result.bytes }] : []) };
}

export async function resolveAssets(references: AssetReferenceDocument, options: ResolvedAssetOptions): Promise<ResolvedAssetDocument> {
  return (await resolveAssetsWithRuntime(references, options)).document;
}
