import type { LayoutEvidenceDocument } from "@aio/layout-evidence";
import type { LayoutInferenceDocument, LayoutInferenceEntry } from "@aio/layout-inference";
import { parseSizingInference, validateSizingInferenceSemantics, type AxisSizingInference, type InferredConstraint, type InferredSizingMode, type SizingCandidate, type SizingConflict, type SizingInferenceDocument, type SizingInferenceEntry, type SizingReason } from "@aio/sizing-inference";
import { DEFAULT_SIZING_INFERENCE_THRESHOLDS, type SizingInferenceThresholds } from "@aio/sizing-inference";
import type { NormalizedElementNode, NormalizedLength, NormalizedPageModel, ParsedCssValue } from "@aio/page-model";

const clamp = (value: number) => Math.max(0, Math.min(1, value));
const finite = (value: number | undefined): value is number => value !== undefined && Number.isFinite(value);
const px = (value: ParsedCssValue<NormalizedLength> | undefined) => { const parsed = value?.value; return value?.parsed && parsed?.type === "PX" && "value" in parsed && finite(parsed.value) ? parsed.value : undefined; };
const rawKind = (raw: string): AxisSizingInference["sourceValue"]["parsedKind"] => { const value = raw.trim().toLowerCase(); if (!value) return "UNPARSED"; if (/^-?(?:\d+\.?\d*|\.\d+)px$/.test(value) || value === "0") return "PX"; if (value.endsWith("%")) return "PERCENT"; if (value === "auto") return "AUTO"; if (/^(calc|clamp|min|max)\(/.test(value)) return "CALC"; if (/(vw|vh|em|rem|ch|ex)$/.test(value)) return "RELATIVE_UNIT"; if (/^(none|normal|fit-content|min-content|max-content)$/.test(value)) return "KEYWORD"; return "UNPARSED"; };
const reason = (code: SizingReason["code"]): SizingReason => ({ code, message: code.toLowerCase().replaceAll("_", " ") });
const conflict = (code: SizingConflict["code"], penalty: number): SizingConflict => ({ code, penalty, message: code.toLowerCase().replaceAll("_", " ") });
const candidate = (mode: InferredSizingMode, score: number, codes: SizingReason["code"][], penalties: SizingConflict[] = []): SizingCandidate => ({ mode, score: clamp(score), evidenceCodes: codes, penaltyCodes: penalties.map((item) => item.code) });
const elements = (root: NormalizedElementNode) => { const map = new Map<string, NormalizedElementNode>(); const visit = (node: NormalizedElementNode) => { map.set(node.id, node); for (const child of node.children) if (child.nodeType === "ELEMENT") visit(child); }; visit(root); return map; };
function relation(parent: NormalizedElementNode | undefined, node: NormalizedElementNode, axis: "width" | "height"): AxisSizingInference["parentRelation"] { if (!parent) return undefined; const sum = (a: number | undefined, b: number | undefined) => (a ?? 0) + (b ?? 0); const padding = axis === "width" ? sum(px(parent.style.box.padding.left), px(parent.style.box.padding.right)) : sum(px(parent.style.box.padding.top), px(parent.style.box.padding.bottom)); const border = axis === "width" ? sum(px(parent.style.box.borderWidth.left), px(parent.style.box.borderWidth.right)) : sum(px(parent.style.box.borderWidth.top), px(parent.style.box.borderWidth.bottom)); const parentSize = axis === "width" ? parent.geometry.documentRect.width : parent.geometry.documentRect.height; const childSize = axis === "width" ? node.geometry.documentRect.width : node.geometry.documentRect.height; const contentSize = Math.max(0, parentSize - padding - border); const ratio = contentSize > 0 ? childSize / contentSize : undefined; return { parentContentSize: contentSize, childMeasuredSize: childSize, ratio, remainingSpace: contentSize - childSize, approximatelyMatchesParent: Math.abs(contentSize - childSize) <= Math.max(4, contentSize * 0.03) }; }
function contentRelation(entry: LayoutEvidenceDocument["entries"][number] | undefined, node: NormalizedElementNode, axis: "width" | "height"): NonNullable<AxisSizingInference["contentRelation"]> { const size = axis === "width" ? entry?.contentBounds?.width : entry?.contentBounds?.height; const measured = axis === "width" ? node.geometry.documentRect.width : node.geometry.documentRect.height; if (size === undefined) return { measuredSize: measured, closelyFitsContent: false }; const delta = measured - size; return { contentBoundsSize: size, measuredSize: measured, delta, ratio: size > 0 ? measured / size : undefined, closelyFitsContent: Math.abs(delta) <= Math.max(6, measured * 0.05) }; }
function constraint(value: ParsedCssValue<NormalizedLength> | undefined): InferredConstraint | undefined { if (!value) return undefined; return { raw: value.raw, value: px(value), parsed: value.parsed }; }
function axisSizing(node: NormalizedElementNode, parent: NormalizedElementNode | undefined, evidence: LayoutEvidenceDocument["entries"][number] | undefined, layout: LayoutInferenceEntry | undefined, axis: "width" | "height", thresholds: SizingInferenceThresholds): { axis: AxisSizingInference; reasons: SizingReason[]; conflicts: SizingConflict[] } {
  const source = axis === "width" ? node.style.sizing.cssWidth : node.style.sizing.cssHeight; const raw = source?.raw ?? ""; const kind = rawKind(raw); const measured = axis === "width" ? node.geometry.documentRect.width : node.geometry.documentRect.height; const parentRelation = relation(parent, node, axis); const content = contentRelation(evidence, node, axis); const reasons: SizingReason[] = [{ ...reason("MEASURED_SIZE_AVAILABLE") }]; const conflicts: SizingConflict[] = []; const candidates: SizingCandidate[] = [];
  const relative = kind === "PERCENT" || kind === "RELATIVE_UNIT" || kind === "CALC"; if (relative) { candidates.push(candidate("RELATIVE", 0.78, ["CSS_SIZE_RELATIVE"])); } else if (kind === "PX") { candidates.push(candidate("FIXED", 0.72, ["CSS_SIZE_FIXED_PX"])); } else if (kind === "AUTO") { candidates.push(candidate("CONTENT", axis === "height" ? 0.62 : 0.48, ["CSS_SIZE_AUTO"])); } else { candidates.push(candidate("UNKNOWN", 0.22, ["INSUFFICIENT_SIZING_EVIDENCE"])); }
  if (parentRelation?.approximatelyMatchesParent) { candidates.push(candidate("STRETCH", 0.64, ["PARENT_CONTENT_MATCH"])); reasons.push(reason("PARENT_CONTENT_MATCH")); }
  if (content.closelyFitsContent) { candidates.push(candidate("CONTENT", 0.68, ["CONTENT_BOUNDS_MATCH"])); reasons.push(reason("CONTENT_BOUNDS_MATCH")); }
  const display = node.style.display.value; const isBlock = display === "BLOCK" || display === "INLINE_BLOCK"; const isInline = display === "INLINE"; const primary = layout?.arrangement.primaryAxis; if (axis === "width" && isBlock && kind === "AUTO" && node.style.position.value !== "ABSOLUTE" && node.style.position.value !== "FIXED") candidates.push(candidate("STRETCH", 0.75, ["BLOCK_AUTO_WIDTH_STRETCH"])); if (axis === "height" && isBlock && kind === "AUTO") candidates.push(candidate("CONTENT", 0.7, ["BLOCK_AUTO_HEIGHT_CONTENT"])); if (isInline) candidates.push(candidate("CONTENT", 0.65, ["INLINE_CONTENT_SIZING"])); if (display === "INLINE_BLOCK" && kind === "AUTO") candidates.push(candidate("CONTENT", 0.67, ["INLINE_BLOCK_CONTENT_SIZING"]));
  const grow = node.style.flex.flexGrow?.value; if (primary === (axis === "width" ? "HORIZONTAL" : "VERTICAL") && typeof grow === "number" && grow >= thresholds.stretchGrowMinimum) candidates.push(candidate("STRETCH", 0.9, ["FLEX_GROW_POSITIVE"])); if (primary === (axis === "width" ? "HORIZONTAL" : "VERTICAL") && node.style.flex.flexBasis?.value?.type === "PX" && node.style.flex.flexBasis.value.value === 0) candidates.push(candidate("STRETCH", 0.82, ["FLEX_BASIS_ZERO"])); if (layout?.mode === "GRID" && parentRelation?.approximatelyMatchesParent) candidates.push(candidate("STRETCH", 0.78, ["GRID_TRACK_STRETCH"]));
  const replaced = ["IMG","SVG","VIDEO","CANVAS","IFRAME","INPUT","TEXTAREA","SELECT"].includes(node.tagName); if (replaced && !relative && kind !== "PX") candidates.push(candidate("INTRINSIC", thresholds.maximumIntrinsicWithoutAssetConfidence, ["REPLACED_ELEMENT_INTRINSIC"])); if (axis === "height" && node.style.sizing.aspectRatioRaw && kind === "AUTO") candidates.push(candidate("INTRINSIC", 0.66, ["CSS_ASPECT_RATIO"]));
  const min = axis === "width" ? node.style.sizing.minWidth : node.style.sizing.minHeight; const max = axis === "width" ? node.style.sizing.maxWidth : node.style.sizing.maxHeight; if (min || max) { if (min) reasons.push(reason("CSS_MIN_CONSTRAINT")); if (max) reasons.push(reason("CSS_MAX_CONSTRAINT")); candidates.push(candidate("CONSTRAINED", 0.7, [min ? "CSS_MIN_CONSTRAINT" : "CSS_MAX_CONSTRAINT"])); }
  const sorted = candidates.sort((a, b) => b.score - a.score).slice(0, 3); const winner = sorted[0] ?? candidate("UNKNOWN", 0.1, ["INSUFFICIENT_SIZING_EVIDENCE"]); const second = sorted[1]; const ambiguous = second !== undefined && winner.score - second.score < thresholds.candidateAmbiguityDelta; const mode = ambiguous ? "UNKNOWN" : winner.score < thresholds.lowConfidence ? "UNKNOWN" : winner.mode; const confidence = clamp(ambiguous ? Math.min(winner.score, 0.5) : winner.score); if (ambiguous) conflicts.push(conflict("CONTENT_AND_STRETCH_CONFLICT", 0.1)); if ((mode === "FIXED" || mode === "RELATIVE") && parentRelation?.approximatelyMatchesParent && kind === "PX") conflicts.push(conflict("FIXED_AND_STRETCH_CONFLICT", 0.12)); if (node.geometry.overflow.ownBox) conflicts.push(conflict("OVERFLOW_AFFECTS_CONTENT_SIZE", 0.05));
  const axisResult: AxisSizingInference = { mode, confidence, measuredSize: measured, candidates: sorted, sourceValue: { raw, parsedKind: kind }, parentRelation, contentRelation: content }; return { axis: axisResult, reasons, conflicts };
}
export function inferPageSizing(model: NormalizedPageModel, evidence: LayoutEvidenceDocument, layout: LayoutInferenceDocument, thresholds: SizingInferenceThresholds = DEFAULT_SIZING_INFERENCE_THRESHOLDS): SizingInferenceDocument { const startedAt = Date.now(); const nodeMap = elements(model.root); const evidenceMap = new Map(evidence.entries.map((entry) => [entry.nodeId, entry])); const layoutMap = new Map(layout.entries.map((entry) => [entry.nodeId, entry])); const entries: SizingInferenceEntry[] = []; const warningMap = new Map<string, { count: number; sampleNodeIds: string[]; message: string }>(); const addWarning = (code: string, nodeId: string) => { const item = warningMap.get(code) ?? { count: 0, sampleNodeIds: [], message: code.toLowerCase().replaceAll("_", " ") }; item.count += 1; if (item.sampleNodeIds.length < 5) item.sampleNodeIds.push(nodeId); warningMap.set(code, item); };
  for (const node of nodeMap.values()) { const parent = node.parentId ? nodeMap.get(node.parentId) : undefined; const item = evidenceMap.get(node.id); const width = axisSizing(node, parent, item, layoutMap.get(node.id), "width", thresholds); const height = axisSizing(node, parent, item, layoutMap.get(node.id), "height", thresholds); const ratioRaw = node.style.sizing.aspectRatioRaw ?? ""; const ratio = /^\d+(?:\.\d+)?(?:\s*\/\s*\d+(?:\.\d+)?)?$/.exec(ratioRaw); let aspectRatio: SizingInferenceEntry["aspectRatio"]; if (ratio) { const parts = ratioRaw.split("/").map((value) => Number(value.trim())); const value = parts.length === 2 && parts[1] ? parts[0]! / parts[1] : parts[0]; aspectRatio = { value, raw: ratioRaw, parsed: true, source: "DECLARED_STYLE", confidence: 0.9 }; } else if (ratioRaw) aspectRatio = { raw: ratioRaw, parsed: false, source: "UNRESOLVED", confidence: 0.2 }; const reasons = [...width.reasons, ...height.reasons].filter((item, index, all) => all.findIndex((candidateItem) => candidateItem.code === item.code) === index); const conflicts = [...width.conflicts, ...height.conflicts]; entries.push({ nodeId: node.id, parentId: node.parentId, horizontal: width.axis, vertical: height.axis, ...(aspectRatio ? { aspectRatio } : {}), constraints: { minWidth: constraint(node.style.sizing.minWidth), maxWidth: constraint(node.style.sizing.maxWidth), minHeight: constraint(node.style.sizing.minHeight), maxHeight: constraint(node.style.sizing.maxHeight) }, reasons, conflicts, fallback: width.axis.mode === "RELATIVE" || height.axis.mode === "RELATIVE" ? "PRESERVE_RELATIVE_SOURCE" : ["IMG","SVG","VIDEO","CANVAS","IFRAME"].includes(node.tagName) ? "PRESERVE_INTRINSIC_SIZE" : node.style.position.value === "ABSOLUTE" || node.style.position.value === "FIXED" ? "PRESERVE_ABSOLUTE_GEOMETRY" : "USE_MEASURED_FIXED_SIZE" }); if (width.axis.confidence < thresholds.mediumConfidence || height.axis.confidence < thresholds.mediumConfidence) addWarning("LOW_CONFIDENCE_SIZING", node.id); }
  const count = (axis: "horizontal" | "vertical", mode: InferredSizingMode) => entries.filter((entry) => entry[axis].mode === mode).length; const result = parseSizingInference({ inferenceVersion: "1.0", source: { modelVersion: model.modelVersion, layoutEvidenceVersion: evidence.evidenceVersion, layoutInferenceVersion: layout.inferenceVersion, requestedUrl: model.source.requestedUrl, finalUrl: model.source.finalUrl, inferredAt: new Date().toISOString() }, entries, metrics: { entryCount: entries.length, horizontalContentCount: count("horizontal", "CONTENT"), horizontalStretchCount: count("horizontal", "STRETCH"), horizontalFixedCount: count("horizontal", "FIXED"), horizontalRelativeCount: count("horizontal", "RELATIVE"), horizontalIntrinsicCount: count("horizontal", "INTRINSIC"), horizontalUnknownCount: count("horizontal", "UNKNOWN"), verticalContentCount: count("vertical", "CONTENT"), verticalStretchCount: count("vertical", "STRETCH"), verticalFixedCount: count("vertical", "FIXED"), verticalRelativeCount: count("vertical", "RELATIVE"), verticalIntrinsicCount: count("vertical", "INTRINSIC"), verticalUnknownCount: count("vertical", "UNKNOWN"), constrainedEntryCount: entries.filter((entry) => entry.horizontal.mode === "CONSTRAINED" || entry.vertical.mode === "CONSTRAINED").length, conflictedEntryCount: entries.filter((entry) => entry.conflicts.length > 0).length, lowConfidenceEntryCount: entries.filter((entry) => entry.horizontal.confidence < thresholds.mediumConfidence || entry.vertical.confidence < thresholds.mediumConfidence).length, inferenceTimeMs: Math.max(0, Date.now() - startedAt) }, warnings: [...warningMap.entries()].map(([code, value]) => ({ code, ...value })) }); validateSizingInferenceSemantics(result, model); return result; }
