import type { NormalizedPageModel } from "@aio/page-model";

export interface AxisEvidence { childCount: number; ordered: boolean; monotonic: boolean; overlapRatio: number; alignmentRatio: number; averageGap?: number | undefined; gapVariance?: number | undefined; }
export interface GapEvidence { values: number[]; count: number; minimum?: number | undefined; maximum?: number | undefined; average?: number | undefined; median?: number | undefined; variance?: number | undefined; coefficientOfVariation?: number | undefined; }
export interface ParentPaddingEvidence { declared: { top?: number | undefined; right?: number | undefined; bottom?: number | undefined; left?: number | undefined }; observed: { top?: number | undefined; right?: number | undefined; bottom?: number | undefined; left?: number | undefined }; difference: { top?: number | undefined; right?: number | undefined; bottom?: number | undefined; left?: number | undefined }; comparable: boolean; }
export interface AlignmentEvidence { leftDeviation?: number | undefined; centerXDeviation?: number | undefined; rightDeviation?: number | undefined; topDeviation?: number | undefined; centerYDeviation?: number | undefined; bottomDeviation?: number | undefined; }
export interface OverlapEvidence { pairCount: number; overlappingPairCount: number; overlapRatio: number; maximumIntersectionArea: number; overlappingPairsSample: Array<{ firstId: string; secondId: string; intersectionArea: number }>; }
export interface LayoutLineGroup { childIds: string[]; start: number; end: number; crossAxisCenter: number; }
export interface WrappingEvidence { rowGroups: LayoutLineGroup[]; columnGroups: LayoutLineGroup[]; }
export interface SizingRelationshipEvidence { widthValues: number[]; heightValues: number[]; widthAverage?: number | undefined; widthVariance?: number | undefined; widthCoefficientOfVariation?: number | undefined; heightAverage?: number | undefined; heightVariance?: number | undefined; heightCoefficientOfVariation?: number | undefined; }
export interface FlexSourceEvidence { displayIsFlex?: boolean | undefined; directionRaw?: string | undefined; wrapRaw?: string | undefined; justifyContentRaw?: string | undefined; alignItemsRaw?: string | undefined; alignContentRaw?: string | undefined; rowGap?: number | undefined; columnGap?: number | undefined; }
export interface GridSourceEvidence { displayIsGrid?: boolean | undefined; templateColumnsRaw?: string | undefined; templateRowsRaw?: string | undefined; autoFlowRaw?: string | undefined; rowGap?: number | undefined; columnGap?: number | undefined; observedRowCount: number; observedColumnCount: number; }
export interface BlockFlowEvidence { displayIsBlockLike: boolean; flowChildCount: number; verticalOrderingRatio: number; horizontalOrderingRatio: number; }
export interface PositionedSourceEvidence { absoluteCount: number; fixedCount: number; relativeCount: number; stickyCount: number; positionedInsideParentRatio: number; positionedOverlapRatio: number; }
export interface LayoutEvidenceEntry { nodeId: string; parentId?: string | undefined; sourceDisplay: string; sourcePosition: string; children: { total: number; elementCount: number; textCount: number; directTextNodeCount: number; nonWhitespaceDirectTextNodeCount: number; flowElementIds: string[]; positionedElementIds: string[]; zeroAreaElementIds: string[] }; contentBounds?: { minX: number; minY: number; maxX: number; maxY: number; width: number; height: number } | undefined; axes: { horizontal: AxisEvidence; vertical: AxisEvidence }; spacing: { horizontalGap: GapEvidence; verticalGap: GapEvidence; parentPadding: ParentPaddingEvidence }; alignment: AlignmentEvidence; overlap: OverlapEvidence; wrapping: WrappingEvidence; sizing: SizingRelationshipEvidence; sourceEvidence: { flex: FlexSourceEvidence; grid: GridSourceEvidence; block: BlockFlowEvidence; positioned: PositionedSourceEvidence }; }
export interface LayoutEvidenceWarning { code: "INSUFFICIENT_CHILDREN" | "MIXED_TEXT_AND_ELEMENT_CHILDREN" | "OVERLAP_ANALYSIS_LIMITED" | "UNCOMPARABLE_PADDING" | "GEOMETRY_INCONSISTENT" | "LAYOUT_EVIDENCE_PARTIAL"; message: string; nodeId?: string | undefined; severity: "INFO" | "WARNING"; }
export interface LayoutEvidenceMetrics { entryCount: number; flexSourceCount: number; gridSourceCount: number; blockSourceCount: number; containersWithMultipleChildren: number; containersWithOverlap: number; containersWithWrappingCandidates: number; containersWithPositionedChildren: number; evidenceTimeMs: number; }
export interface LayoutEvidenceDocument { evidenceVersion: "1.0"; source: { modelVersion: "1.0"; requestedUrl: string; finalUrl: string; capturedAt: string }; entries: LayoutEvidenceEntry[]; metrics: LayoutEvidenceMetrics; warnings: LayoutEvidenceWarning[]; }
export type LayoutEvidenceInput = NormalizedPageModel;
